import React, { useEffect, useMemo, useState } from "react";
import { Calculator, Copy, FileDown, Plus, Search, Settings2, Trash2, Wrench } from "lucide-react";
import { supabase } from "../../lib/supabase";

const defaults = { tractor_rate: 145, trailer_rate: 135, diagnostic_rate: 155, after_hours_rate: 75, weekend_rate: 75, holiday_rate: 125, minimum_labor_hours: 1, service_call_rate: 95, mileage_rate: 2.25 };
const blankLine = { parts: 0, shopSupplies: 0, serviceCall: 0, mileage: 0, afterHours: 0, tax: 0, discount: 0 };
const blankOperation = { vehicle_type: "Tractor", category_id: "", component_name: "", operation_name: "", operation_type: "repair", minimum_hours: 1, standard_hours: 1.5, maximum_hours: 2, difficulty: "Moderate", description: "", common_symptoms: "", technical_notes: "", image_url: "", is_active: true };

export default function FlatRateGuide({ session, role, onCreateJob }) {
  const isAdmin = role === "admin";
  const [operations, setOperations] = useState([]), [categories, setCategories] = useState([]), [rates, setRates] = useState(defaults);
  const [query, setQuery] = useState(""), [vehicle, setVehicle] = useState("All"), [category, setCategory] = useState("All"), [type, setType] = useState("All");
  const [estimate, setEstimate] = useState([]), [extras, setExtras] = useState(blankLine), [notice, setNotice] = useState("");
  const [adminOpen, setAdminOpen] = useState(false), [editing, setEditing] = useState(null), [jobs, setJobs] = useState([]), [jobId, setJobId] = useState(localStorage.getItem("flat-rate-job-id") || "");
  const [managePartsFor,setManagePartsFor]=useState(null);
  const [estimateParts] = useState(() => JSON.parse(localStorage.getItem("parts-estimate") || "[]"));

  async function load() {
    const [op, cat, rate, job] = await Promise.all([
      supabase.from("flat_rate_operations").select("*,flat_rate_categories(name)").order("operation_name"),
      supabase.from("flat_rate_categories").select("*").order("sort_order"),
      supabase.from("labor_rate_settings").select("*").limit(1).maybeSingle(),
      supabase.from("jobs").select("id,invoice_number,company").order("job_date", { ascending: false }).limit(100),
    ]);
    if (!op.error) setOperations(op.data || []); if (!cat.error) setCategories(cat.data || []); if (rate.data) setRates({ ...defaults, ...rate.data }); if (!job.error) setJobs(job.data || []);
  }
  useEffect(() => { load(); }, []);

  const filtered = useMemo(() => operations.filter((op) => {
    const hay = `${op.operation_name} ${op.component_name} ${op.description} ${op.common_symptoms}`.toLowerCase();
    return (isAdmin || op.is_active) && (vehicle === "All" || op.vehicle_type === vehicle) && (category === "All" || String(op.category_id) === category) && (type === "All" || op.operation_type === type) && hay.includes(query.toLowerCase());
  }), [operations, query, vehicle, category, type, isAdmin]);

  function add(op) { setEstimate((x) => [...x, { ...op, lineId: crypto.randomUUID(), hourMode: "standard", quantity: 1, hours: Number(op.standard_hours), rate: Number(op.vehicle_type === "Tractor" ? rates.tractor_rate : rates.trailer_rate) }]); }
  function updateLine(id, patch) { setEstimate((x) => x.map((l) => l.lineId === id ? { ...l, ...patch } : l)); }
  const laborHours = estimate.reduce((n, l) => n + Number(l.hours) * Number(l.quantity), 0);
  const laborTotal = estimate.reduce((n, l) => n + Number(l.hours) * Number(l.quantity) * Number(l.rate), 0);
  const linkedPartsTotal = estimateParts.reduce((n,p)=>n+Number(p.quantity)*Number(p.unit_price)+Number(p.core_charge),0);
  const subtotal = laborTotal + linkedPartsTotal + Number(extras.parts) + Number(extras.shopSupplies) + Number(extras.serviceCall) + Number(extras.mileage) + Number(extras.afterHours);
  const total = subtotal + subtotal * Number(extras.tax) / 100 - Number(extras.discount);

  async function attachToJob() {
    if (!jobId || !estimate.length) return setNotice("Select a job and at least one labor operation.");
    const rows = estimate.map((l) => ({ job_id: jobId, flat_rate_operation_id: l.id, operation_name: l.operation_name, hours_type: l.hourMode, hours: Number(l.hours) * Number(l.quantity), quantity: l.quantity, labor_rate: l.rate, created_by: session?.authUserId || session?.id }));
    const { error } = await supabase.from("job_labor_operations").insert(rows); setNotice(error ? error.message : "Labor operations added to the job.");
  }
  function copyEstimate() { navigator.clipboard.writeText(estimateText(estimate, laborHours, laborTotal, total)); setNotice("Estimate copied."); }
  function printEstimate() { const w = window.open("", "_blank"); if (!w) return setNotice("Allow popups to print the estimate."); w.document.write(`<html><body><pre>${escapeHtml(estimateText(estimate, laborHours, laborTotal, total))}</pre><script>window.print()<\/script></body></html>`); w.document.close(); }
  async function saveEstimate() { localStorage.setItem("flat-rate-estimate", JSON.stringify({ estimate, extras, total, savedAt: new Date().toISOString() })); setNotice("Estimate saved on this device."); }
  async function saveRates() { const { id, created_at, updated_at, ...payload } = rates; const result = id ? await supabase.from("labor_rate_settings").update(payload).eq("id", id) : await supabase.from("labor_rate_settings").insert(payload); setNotice(result.error ? result.error.message : "Labor rates saved."); if (!result.error) load(); }
  async function saveOperation(event) { event.preventDefault(); const fields = Object.keys(blankOperation); const payload = Object.fromEntries(fields.map(k=>[k,editing[k]])); if (!editing.id) payload.created_by=session?.authUserId||session?.id; const result = editing.id ? await supabase.from("flat_rate_operations").update(payload).eq("id", editing.id) : await supabase.from("flat_rate_operations").insert(payload); setNotice(result.error ? result.error.message : "Catalog operation saved."); if (!result.error) { setEditing(null); load(); } }
  async function removeOperation(op) { if (!confirm(`Delete ${op.operation_name}?`)) return; const { error } = await supabase.from("flat_rate_operations").delete().eq("id", op.id); setNotice(error ? error.message : "Operation deleted."); if (!error) load(); }

  return <div className="min-h-screen bg-slate-100 p-4 md:p-6">
    <div className="mb-4 flex flex-wrap items-start justify-between gap-3 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div><p className="text-xs font-black uppercase tracking-[.18em] text-blue-600">Interactive Flat Rate Guide</p><h1 className="mt-1 text-2xl font-black text-slate-950">Labor catalog & estimate builder</h1><p className="mt-1 text-sm font-medium text-slate-500">All labor times are configurable estimates, not guaranteed repair times.</p></div>{isAdmin && <button onClick={() => setAdminOpen(!adminOpen)} className="flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white"><Settings2 className="h-4 w-4"/> Admin configuration</button>}</div>
    {notice && <div className="mb-4 rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm font-bold text-blue-800">{notice}</div>}
    {adminOpen && isAdmin && <AdminPanel rates={rates} setRates={setRates} saveRates={saveRates} categories={categories} editing={editing} setEditing={setEditing} saveOperation={saveOperation} />}
    {managePartsFor&&isAdmin&&<OperationPartsManager operation={managePartsFor} onClose={()=>setManagePartsFor(null)}/>}
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1.35fr)_minmax(360px,.65fr)]">
      <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="mb-4 grid gap-2 md:grid-cols-4"><label className="relative md:col-span-2"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search operations, symptoms, components" className="w-full rounded-xl border border-slate-300 py-2.5 pl-9 pr-3 text-sm"/></label><Filter value={vehicle} set={setVehicle} values={["All","Tractor","53' Dry Van Trailer"]}/><Filter value={type} set={setType} values={["All","inspect","diagnose","repair","replace","adjust"]}/><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2 text-sm md:col-span-2"><option value="All">All systems</option>{categories.filter(c=>vehicle==="All"||c.vehicle_type===vehicle).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>
        <div className="grid max-h-[720px] gap-3 overflow-y-auto pr-1 md:grid-cols-2">{filtered.map(op=><article key={op.id} className="rounded-xl border border-slate-200 p-4"><div className="flex justify-between gap-3"><div><p className="text-[11px] font-black uppercase text-blue-600">{op.vehicle_type} · {op.flat_rate_categories?.name}</p><h3 className="mt-1 font-black text-slate-950">{op.operation_name}</h3><p className="text-xs font-semibold text-slate-500">{op.component_name} · {op.operation_type} · {op.difficulty}</p></div><Wrench className="h-5 w-5 text-slate-400"/></div><p className="mt-3 line-clamp-2 text-sm text-slate-600">{op.description}</p><div className="mt-3 flex items-center justify-between"><span className="text-xs font-bold text-slate-500">{op.minimum_hours} / <b className="text-slate-900">{op.standard_hours}</b> / {op.maximum_hours} hrs</span><div className="flex gap-1">{isAdmin&&<><button onClick={()=>setManagePartsFor(op)} className="rounded-lg bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-700">Parts</button><button onClick={()=>setEditing({...op})} className="rounded-lg bg-slate-100 px-2 py-1 text-xs font-bold">Edit</button><button onClick={()=>removeOperation(op)} className="rounded-lg bg-red-50 p-1.5 text-red-700"><Trash2 className="h-3.5 w-3.5"/></button></>}<button onClick={()=>add(op)} className="flex items-center gap-1 rounded-lg bg-blue-600 px-3 py-1.5 text-xs font-bold text-white"><Plus className="h-3.5 w-3.5"/> Add</button></div></div></article>)}</div>
      </section>
      <aside className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-center gap-2"><Calculator className="h-5 w-5 text-blue-600"/><h2 className="text-lg font-black">Estimate builder</h2></div><div className="mt-4 space-y-3">{estimate.map(l=><div key={l.lineId} className="rounded-xl border border-slate-200 bg-slate-50 p-3"><div className="flex justify-between"><p className="text-sm font-black">{l.operation_name}</p><button onClick={()=>setEstimate(x=>x.filter(i=>i.lineId!==l.lineId))}><Trash2 className="h-4 w-4 text-red-600"/></button></div><div className="mt-2 grid grid-cols-3 gap-2"><select value={l.hourMode} onChange={e=>{const m=e.target.value;updateLine(l.lineId,{hourMode:m,hours:Number(l[`${m}_hours`])})}} className="rounded-lg border p-2 text-xs"><option value="minimum">Minimum</option><option value="standard">Standard</option><option value="maximum">Maximum</option></select><input aria-label="Quantity" type="number" min="1" value={l.quantity} onChange={e=>updateLine(l.lineId,{quantity:e.target.value})} className="rounded-lg border p-2 text-xs"/><input aria-label="Labor rate" type="number" value={l.rate} onChange={e=>updateLine(l.lineId,{rate:e.target.value})} className="rounded-lg border p-2 text-xs"/></div><p className="mt-2 text-right text-sm font-black">${(l.hours*l.quantity*l.rate).toFixed(2)}</p></div>)}</div>
        {estimateParts.length>0&&<div className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-3"><p className="text-xs font-black uppercase text-emerald-800">Parts Intelligence selections</p>{estimateParts.map(p=><div key={p.id} className="mt-1 flex justify-between text-xs"><span>{p.quantity}× {p.part_name}</span><b>${(p.quantity*p.unit_price+p.core_charge).toFixed(2)}</b></div>)}</div>}
        <div className="mt-4 grid grid-cols-2 gap-2">{[["Additional parts","parts"],["Shop supplies","shopSupplies"],["Service call","serviceCall"],["Mileage","mileage"],["After-hours fee","afterHours"],["Tax %","tax"],["Discount","discount"]].map(([label,key])=><label key={key} className="text-xs font-bold text-slate-600">{label}<input type="number" value={extras[key]} onChange={e=>setExtras({...extras,[key]:e.target.value})} className="mt-1 w-full rounded-lg border p-2 text-sm"/></label>)}</div>
        <div className="mt-4 border-t pt-3 text-sm"><Row label="Labor hours" value={laborHours.toFixed(2)}/><Row label="Labor total" value={`$${laborTotal.toFixed(2)}`}/><Row label="Parts & cores" value={`$${linkedPartsTotal.toFixed(2)}`}/><Row label="Estimated grand total" value={`$${Math.max(0,total).toFixed(2)}`} strong/></div>
        <select value={jobId} onChange={e=>setJobId(e.target.value)} className="mt-4 w-full rounded-xl border p-2.5 text-sm"><option value="">Select current job</option>{jobs.map(j=><option key={j.id} value={j.id}>{j.invoice_number||j.id} — {j.company||"No company"}</option>)}</select><div className="mt-3 grid grid-cols-2 gap-2"><Action onClick={attachToJob} text="Add to Current Job"/><Action onClick={()=>onCreateJob?.()} text="Create New Job"/><Action onClick={saveEstimate} text="Save Estimate"/><Action onClick={printEstimate} text="Print / Export PDF" icon={FileDown}/><Action onClick={copyEstimate} text="Copy Estimate" icon={Copy}/></div>
      </aside>
    </div>
  </div>;
}

function AdminPanel({rates,setRates,saveRates,categories,editing,setEditing,saveOperation}) { return <section className="mb-4 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 className="font-black">Admin configuration</h2><div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{Object.keys(defaults).map(k=><label key={k} className="text-xs font-bold capitalize text-slate-600">{k.replaceAll("_"," ")}<input type="number" step=".01" value={rates[k]} onChange={e=>setRates({...rates,[k]:e.target.value})} className="mt-1 w-full rounded-lg border p-2"/></label>)}</div><div className="mt-3 flex gap-2"><button onClick={saveRates} className="rounded-lg bg-blue-600 px-3 py-2 text-sm font-bold text-white">Save rates</button><button onClick={()=>setEditing({...blankOperation})} className="rounded-lg bg-slate-900 px-3 py-2 text-sm font-bold text-white">New operation</button></div>{editing&&<form onSubmit={saveOperation} className="mt-4 grid gap-2 rounded-xl bg-slate-50 p-3 md:grid-cols-3"><Filter value={editing.vehicle_type} set={v=>setEditing({...editing,vehicle_type:v})} values={["Tractor","53' Dry Van Trailer"]}/><select required value={editing.category_id||""} onChange={e=>setEditing({...editing,category_id:e.target.value})} className="rounded-lg border p-2"><option value="">System/category</option>{categories.filter(c=>c.vehicle_type===editing.vehicle_type).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select>{["component_name","operation_name","minimum_hours","standard_hours","maximum_hours","difficulty","description","common_symptoms","technical_notes","image_url"].map(k=><input key={k} required={["component_name","operation_name"].includes(k)} type={k.includes("hours")?"number":"text"} step=".1" placeholder={k.replaceAll("_"," ")} value={editing[k]??""} onChange={e=>setEditing({...editing,[k]:e.target.value})} className="rounded-lg border p-2 text-sm"/>)}<Filter value={editing.operation_type} set={v=>setEditing({...editing,operation_type:v})} values={["inspect","diagnose","repair","replace","adjust"]}/><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={editing.is_active} onChange={e=>setEditing({...editing,is_active:e.target.checked})}/> Active</label><div className="flex gap-2"><button className="rounded-lg bg-blue-600 px-3 py-2 text-sm font-bold text-white">Save operation</button><button type="button" onClick={()=>setEditing(null)} className="rounded-lg bg-white px-3 py-2 text-sm font-bold">Cancel</button></div></form>}</section> }
function Filter({value,set,values}) { return <select value={value} onChange={e=>set(e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2 text-sm">{values.map(v=><option key={v}>{v}</option>)}</select> }
function Row({label,value,strong}) { return <div className={`flex justify-between py-1 ${strong?"mt-2 text-lg font-black":"font-semibold"}`}><span>{label}</span><span>{value}</span></div> }
function Action({onClick,text,icon:Icon}) { return <button onClick={onClick} className="flex items-center justify-center gap-1 rounded-xl bg-slate-900 px-2 py-2 text-xs font-bold text-white">{Icon&&<Icon className="h-3.5 w-3.5"/>}{text}</button> }
function estimateText(lines,hours,labor,total) { return `NTTR Flat Rate Estimate\nConfigurable estimate — not a guaranteed repair time.\n\n${lines.map(l=>`${l.operation_name}: ${Number(l.hours)*Number(l.quantity)} hrs @ $${l.rate} = $${(l.hours*l.quantity*l.rate).toFixed(2)}`).join("\n")}\n\nLabor hours: ${hours.toFixed(2)}\nLabor total: $${labor.toFixed(2)}\nEstimated grand total: $${Math.max(0,total).toFixed(2)}` }
function escapeHtml(s){return s.replace(/[&<>]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[c]))}
function OperationPartsManager({operation,onClose}){const [parts,setParts]=useState([]),[links,setLinks]=useState([]),[partId,setPartId]=useState("");async function load(){const [p,l]=await Promise.all([supabase.from("parts_catalog").select("id,part_name,part_number").eq("is_active",true).order("part_name"),supabase.from("flat_rate_operation_parts").select("*,parts_catalog(part_name,part_number)").eq("operation_id",operation.id)]);setParts(p.data||[]);setLinks(l.data||[])}useEffect(()=>{load()},[]);async function addLink(){if(!partId)return;await supabase.from("flat_rate_operation_parts").insert({operation_id:operation.id,part_id:partId,recommendation_type:"recommended",is_required:false,default_quantity:1,default_selected:true});setPartId("");load()}async function change(id,patch){await supabase.from("flat_rate_operation_parts").update(patch).eq("id",id);load()}return <section className="mb-4 rounded-2xl border border-emerald-200 bg-white p-4 shadow-sm"><div className="flex justify-between"><div><h3 className="font-black">Recommended parts · {operation.operation_name}</h3><p className="text-xs text-slate-500">Configure required, recommended, optional, quantity, and default selection.</p></div><button onClick={onClose} className="text-sm font-bold">Close</button></div><div className="mt-3 flex gap-2"><select value={partId} onChange={e=>setPartId(e.target.value)} className="min-w-0 flex-1 rounded-lg border p-2 text-sm"><option value="">Choose catalog part</option>{parts.map(p=><option key={p.id} value={p.id}>{p.part_name} · {p.part_number||"Generic"}</option>)}</select><button onClick={addLink} className="rounded-lg bg-emerald-600 px-3 text-sm font-bold text-white">Link</button></div><div className="mt-3 space-y-2">{links.map(l=><div key={l.id} className="grid gap-2 rounded-lg bg-slate-50 p-2 text-xs md:grid-cols-[1fr_130px_80px_110px]"><b>{l.parts_catalog?.part_name}</b><select value={l.recommendation_type} onChange={e=>change(l.id,{recommendation_type:e.target.value,is_required:e.target.value==="required"})} className="rounded border p-1"><option>required</option><option>recommended</option><option>optional</option></select><input type="number" min=".01" step=".01" value={l.default_quantity} onChange={e=>change(l.id,{default_quantity:e.target.value})} className="rounded border p-1"/><label className="flex items-center gap-1"><input type="checkbox" checked={l.default_selected} onChange={e=>change(l.id,{default_selected:e.target.checked})}/>Default selected</label></div>)}</div></section>}
