import React, { useEffect, useMemo, useRef, useState } from "react";
import {
  AlertTriangle, Banknote, BarChart3, Building2, CalendarDays, CheckCircle2, ChevronRight, CircleDollarSign,
  ClipboardList, Download, FileSpreadsheet, FileText, Gauge, History, LoaderCircle, ReceiptText, RefreshCw,
  Printer, Search, Settings, ShieldAlert, SlidersHorizontal, Users, WalletCards, X,
} from "lucide-react";
import {
  ACCOUNTING_DATE_PRESETS, OUTSTANDING_DATE_PRESETS, aggregatePerformance, accountingDateRange, buildAccountingModel,
  buildOutstandingSentInvoices, buildProfitReconciliation, detailRowsForKpi, estimatedProfit, filterOutstandingInvoices,
  isCancelled, isCompleted, isDryRun, isPendingTechPayment, lower, numberValue, profitMargin, summarizeOutstandingInvoices,
} from "./accountingData.js";
import {
  loadAccountingWorkspace, loadTransactionPage, logAccountingExport, recordInvoicePayment, recordTechnicianPayment,
  saveAccountingSettings, voidInvoicePayment, voidTechnicianPayment,
} from "./accountingService.js";
import AccountingExportCenter from "./AccountingExportCenter.jsx";
import { exportOutstandingInvoices } from "./outstandingInvoiceExports.js";

const tabs = ["Overview", "Customer Invoices", "Accounts Receivable", "Technician Payments", "Profitability", "Internal Control", "Accounting Exports", "Settings"];
const moneyFormat = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });

export default function AccountingCenter({ session, onOpenJob }) {
  const [activeTab, setActiveTab] = useState("Overview");
  const [datePreset, setDatePreset] = useState("This Month");
  const [customRange, setCustomRange] = useState({ from: "", to: "" });
  const [workspace, setWorkspace] = useState({ jobs: [], allJobs: [], pendingTechJobs: [], redJobs: [], paymentSummaries: [], settings: null, recentAudit: [] });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [drilldown, setDrilldown] = useState(null);
  const [outstandingOpen, setOutstandingOpen] = useState(false);
  const defaultRangeApplied = useRef(false);
  const range = useMemo(() => accountingDateRange(datePreset, customRange), [datePreset, customRange]);
  const model = useMemo(() => buildAccountingModel(workspace.jobs, workspace.paymentSummaries), [workspace.jobs, workspace.paymentSummaries]);
  const outstanding = useMemo(() => buildOutstandingSentInvoices(workspace.allJobs, workspace.paymentSummaries), [workspace.allJobs, workspace.paymentSummaries]);

  async function refresh() {
    setLoading(true); setError("");
    try { setWorkspace(await loadAccountingWorkspace(range)); }
    catch (loadError) { setError(loadError.message || "Unable to load Accounting Center."); }
    finally { setLoading(false); }
  }
  useEffect(() => { refresh(); }, [range?.from, range?.to]);
  useEffect(() => { const configured=workspace.settings?.default_report_date_range; if(!defaultRangeApplied.current&&ACCOUNTING_DATE_PRESETS.includes(configured)){defaultRangeApplied.current=true;setDatePreset(configured)} }, [workspace.settings]);
  function show(message) { setNotice(message); window.setTimeout(() => setNotice(""), 4500); }
  function openKpi(kpiKey, label) { setDrilldown({ label, rows: detailRowsForKpi(model, kpiKey), kpiKey }); }

  return (
    <div className="min-h-screen bg-[#eef2f7] p-3 sm:p-5 xl:p-7">
      <div className="mx-auto max-w-[1900px] space-y-5">
        <header className="overflow-hidden rounded-3xl bg-[#07182d] text-white shadow-xl">
          <div className="border-b border-white/10 px-5 py-5 sm:px-7">
            <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between">
              <div><p className="text-xs font-black uppercase tracking-[.2em] text-blue-300">Billing / Finance</p><h1 className="mt-1 text-3xl font-black tracking-tight">Accounting Center</h1><p className="mt-1 text-sm font-semibold text-slate-400">NTTR Financial Operations & Accounts Control</p></div>
              <div className="flex flex-wrap items-center gap-2">
                <select value={datePreset} onChange={(event) => setDatePreset(event.target.value)} className="h-11 rounded-xl border border-white/10 bg-[#10233c] px-3 text-sm font-bold text-white">{ACCOUNTING_DATE_PRESETS.map((preset) => <option key={preset}>{preset}</option>)}</select>
                {datePreset === "Custom Range" && <><input type="date" value={customRange.from} onChange={(event) => setCustomRange((current) => ({ ...current, from: event.target.value }))} className="h-11 rounded-xl border border-white/10 bg-[#10233c] px-3 text-white" /><input type="date" value={customRange.to} onChange={(event) => setCustomRange((current) => ({ ...current, to: event.target.value }))} className="h-11 rounded-xl border border-white/10 bg-[#10233c] px-3 text-white" /></>}
                <button type="button" onClick={refresh} className="flex h-11 items-center gap-2 rounded-xl bg-blue-600 px-4 font-black hover:bg-blue-500"><RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />Refresh</button>
              </div>
            </div>
          </div>
          <nav className="flex gap-1 overflow-x-auto px-3 py-3 sm:px-5" aria-label="Accounting Center sections">{tabs.map((tab) => <button key={tab} type="button" onClick={() => setActiveTab(tab)} className={`min-h-10 shrink-0 rounded-xl px-3.5 text-sm font-black transition ${activeTab === tab ? "bg-white text-slate-950" : "text-slate-300 hover:bg-white/10"}`}>{tab}</button>)}</nav>
        </header>

        {notice && <div className="fixed right-5 top-5 z-[180] rounded-xl bg-emerald-600 px-5 py-3 font-black text-white shadow-xl">{notice}</div>}
        {error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 font-bold text-red-800">{error}</div>}
        {loading && !workspace.jobs.length ? <LoadingPanel /> : <>
          {activeTab === "Overview" && <Overview model={model} outstanding={outstanding} audit={workspace.recentAudit} onKpi={openKpi} onOutstanding={() => setOutstandingOpen(true)} onTab={setActiveTab} />}
          {activeTab === "Customer Invoices" && <CustomerInvoices jobs={model.jobs} onOpenJob={onOpenJob} />}
          {activeTab === "Accounts Receivable" && <AccountsReceivable model={model} settings={workspace.settings} onOpenJob={onOpenJob} onChanged={async (message) => { show(message); await refresh(); }} />}
          {activeTab === "Technician Payments" && <TechnicianPayments jobs={model.jobs} allPendingJobs={workspace.pendingTechJobs} settings={workspace.settings} onOpenJob={onOpenJob} onChanged={async (message) => { show(message); await refresh(); }} />}
          {activeTab === "Profitability" && <Profitability jobs={model.jobs} onOpenJob={onOpenJob} />}
          {activeTab === "Internal Control" && <InternalControl jobs={workspace.redJobs} onOpenJob={onOpenJob} />}
          {activeTab === "Accounting Exports" && <AccountingExportCenter model={model} settings={workspace.settings} session={session} rangeLabel={rangeLabel(datePreset, customRange)} onNotice={show} />}
          {activeTab === "Settings" && <AccountingSettings settings={workspace.settings} onSaved={(settings) => { setWorkspace((current) => ({ ...current, settings })); show("Accounting settings saved."); }} />}
        </>}
      </div>
      {drilldown && <SmartKpiDrilldown {...drilldown} onClose={() => setDrilldown(null)} onOpenJob={onOpenJob} />}
      {outstandingOpen && <OutstandingSentInvoicesReport source={outstanding} settings={workspace.settings} session={session} onClose={() => setOutstandingOpen(false)} onOpenJob={onOpenJob} onChanged={async (message) => { show(message); await refresh(); }} />}
    </div>
  );
}

function Overview({ model, outstanding, audit, onKpi, onOutstanding, onTab }) {
  const cards = [
    ["totalBilled", "Total Billed", model.kpis.totalBilled, CircleDollarSign, "money", "blue"], ["partsExpense", "Parts Expense", model.kpis.partsExpense, ReceiptText, "money", "slate"],
    ["techLaborExpense", "Tech Labor Expense", model.kpis.techLaborExpense, Users, "money", "slate"], ["estimatedProfit", "Estimated Profit", model.kpis.estimatedProfit, BarChart3, "money", "green"],
    ["totalJobs", "Total Jobs", model.kpis.totalJobs, ClipboardList, "count", "blue"], ["completedJobs", "Completed Jobs", model.kpis.completedJobs, CheckCircle2, "count", "green"],
    ["cancelledJobs", "Cancelled Jobs", model.kpis.cancelledJobs, X, "count", "red"], ["dryRuns", "Dry Runs", model.kpis.dryRuns, AlertTriangle, "count", "orange"],
    ["techPaymentsDue", "Tech Payments Due", model.kpis.techPaymentsDue, WalletCards, "money", "orange"], ["pendingTechPaymentJobs", "Pending Tech Payment Jobs", model.kpis.pendingTechPaymentJobs, History, "count", "orange"],
    ["redInternalControlJobs", "Red Internal Control Jobs", model.kpis.redInternalControlJobs, ShieldAlert, "count", "red"], ["openCustomerInvoices", "Open Customer Invoices", model.kpis.openCustomerInvoices, FileText, "count", "blue"],
  ];
  return <div className="space-y-5">
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-6"><OutstandingKpiCard value={outstanding.totalOutstanding} count={outstanding.invoiceCount} onClick={onOutstanding} />{cards.map(([key,label,value,Icon,type,tone]) => <KpiCard key={key} label={label} value={type === "money" ? money(value) : number(value)} icon={Icon} tone={tone} onClick={() => onKpi(key,label)} />)}</section>
    {model.warnings.length > 0 && <button type="button" onClick={() => onTab("Internal Control")} className="flex w-full items-center justify-between rounded-2xl border border-amber-200 bg-amber-50 p-4 text-left"><span className="flex items-center gap-3"><AlertTriangle className="h-5 w-5 text-amber-600" /><span><strong className="block text-amber-950">{model.warnings.length} accounting data-quality warnings</strong><span className="text-sm text-amber-800">Review exceptions without modifying source records.</span></span></span><ChevronRight className="h-5 w-5 text-amber-700" /></button>}
    <section className="grid gap-4 xl:grid-cols-3"><SummaryPanel title="Revenue & Expenses" rows={[["Total Billed",money(model.kpis.totalBilled)],["Parts Expense",money(model.kpis.partsExpense)],["Tech Labor Expense",money(model.kpis.techLaborExpense)],["Estimated Job Profit",money(model.kpis.estimatedProfit)]]} /><BreakdownPanel title="Job Status" values={model.statusBreakdown} /><BreakdownPanel title="Invoice Status" values={model.invoiceBreakdown} /></section>
    <section className="grid gap-4 xl:grid-cols-4"><Ranking title="Top Customers" rows={model.topCustomers} /><Ranking title="Top Technicians" rows={model.topTechnicians} /><Ranking title="Top Cities" rows={model.topCities} /><Ranking title="Top Dispatchers" rows={model.topDispatchers} /></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 className="font-black text-slate-950">Recent Financial Activity</h2><div className="mt-3 divide-y divide-slate-100">{audit.length ? audit.slice(0,8).map((item) => <div key={item.id} className="flex flex-col gap-1 py-3 sm:flex-row sm:justify-between"><div><p className="font-bold text-slate-800">{item.action}</p><p className="text-xs text-slate-500">{item.performed_by_name} · {item.record_type}</p></div><span className="text-xs font-semibold text-slate-500">{dateTime(item.created_at)}</span></div>) : <Empty label="No Accounting Center activity recorded yet." />}</div></section>
  </div>;
}

function CustomerInvoices({ jobs, onOpenJob }) {
  const [status, setStatus] = useState("All"); const [search, setSearch] = useState(""); const [company, setCompany] = useState("All"); const [city, setCity] = useState("All"); const [dispatcher, setDispatcher] = useState("All"); const [technician, setTechnician] = useState("All");
  const filtered = useMemo(() => jobs.filter((job) => (status === "All" || job.invoiceStatus === status) && (company === "All" || job.company === company) && (city === "All" || job.city === city) && (dispatcher === "All" || job.dispatcher === dispatcher) && (technician === "All" || job.technician === technician) && matches(job, search)), [jobs,status,company,city,dispatcher,technician,search]);
  return <ReportSection title="Customer Invoices" subtitle={`${filtered.length} invoices from production job records`} icon={FileText}><FilterBar search={search} setSearch={setSearch}>{selectControl("Invoice Status",status,setStatus,["All","Sent","Pending","Paid","Cancelled"])}{selectControl("Company",company,setCompany,unique(jobs,"company"))}{selectControl("City",city,setCity,unique(jobs,"city"))}{selectControl("Dispatcher",dispatcher,setDispatcher,unique(jobs,"dispatcher"))}{selectControl("Technician",technician,setTechnician,unique(jobs,"technician"))}</FilterBar><WideTable headers={["Invoice #","Date","Company","Reference #","Location","Job Status","Invoice Status","Payment Method","Total Bill","Parts","Tech Labor","Estimated Profit","Dispatcher","Technician","Updates","Actions"]}>{filtered.map((job) => <tr key={job.id} className="border-t border-slate-100 even:bg-slate-50"><LinkCell label={job.invoiceNumber || "-"} job={job} onOpenJob={onOpenJob} /><Cell>{date(job.date)}</Cell><Cell strong>{job.company || "-"}</Cell><LinkCell label={job.referenceNumber || "-"} job={job} onOpenJob={onOpenJob} /><Cell>{job.location || "-"}</Cell><Cell><Status value={job.status} /></Cell><Cell><Status value={job.invoiceStatus} /></Cell><Cell>{job.paymentMethod || "-"}</Cell><MoneyCell value={job.totalBill} /><MoneyCell value={job.parts} /><MoneyCell value={job.techLabor} /><MoneyCell value={estimatedProfit(job)} strong /><Cell>{job.dispatcher || "-"}</Cell><Cell>{job.technician || "-"}</Cell><Cell wide>{job.updates || "-"}</Cell><Cell><button onClick={() => onOpenJob?.(job.id)} className="font-black text-blue-700">Open</button></Cell></tr>)}</WideTable></ReportSection>;
}

function AccountsReceivable({ model, settings, onOpenJob, onChanged }) {
  const [paymentJob, setPaymentJob] = useState(null); const [historyOpen, setHistoryOpen] = useState(false);
  const agingKeys = ["Current","1-30 Days","31-60 Days","61-90 Days","91+ Days","Due Date Not Set"];
  return <div className="space-y-4"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MiniKpi label="Total Accounts Receivable" value={money(model.accountsReceivable)} /><MiniKpi label="Partially Paid Invoices" value={number(model.partialInvoices)} /><MiniKpi label="Unpaid Invoices" value={number(model.unpaidInvoices)} /><button onClick={() => setHistoryOpen(true)} className="rounded-2xl bg-[#0b1f3a] p-4 text-left text-white"><History className="h-5 w-5 text-blue-300" /><p className="mt-2 text-xs font-black uppercase text-slate-400">Payment Transactions</p><p className="mt-1 font-black">View paginated history</p></button></section><section className="grid gap-3 sm:grid-cols-3 xl:grid-cols-6">{agingKeys.map((key) => <MiniKpi key={key} label={key} value={money(model.aging[key] || 0)} compact warning={key === "Due Date Not Set" && model.aging[key] > 0} />)}</section>
    <ReportSection title="Accounts Receivable Report" subtitle="Balances come only from non-voided invoice payment transactions" icon={Banknote}><WideTable headers={["Invoice #","Invoice Date","Due Date","Company","Reference #","Total Bill","Amount Paid","Balance Due","Days Outstanding","Aging Bucket","Payment Status","Last Payment Date","Actions"]}>{model.receivables.map((row) => <tr key={row.id} className="border-t border-slate-100 even:bg-slate-50"><LinkCell label={row.invoiceNumber || "-"} job={row} onOpenJob={onOpenJob} /><Cell>{row.invoiceDate ? date(row.invoiceDate) : "NOT SET"}</Cell><Cell warning={!row.invoiceDueDate}>{row.invoiceDueDate ? date(row.invoiceDueDate) : "DUE DATE NOT SET"}</Cell><Cell strong>{row.company || "-"}</Cell><LinkCell label={row.referenceNumber || "-"} job={row} onOpenJob={onOpenJob} /><MoneyCell value={row.totalBill} /><MoneyCell value={row.amountPaid} /><MoneyCell value={row.balanceDue} strong /><Cell>{row.daysOutstanding ?? "-"}</Cell><Cell>{row.agingBucket}</Cell><Cell><Status value={row.paymentStatus} /></Cell><Cell>{row.lastPaymentDate ? date(row.lastPaymentDate) : "-"}</Cell><Cell><button disabled={row.paymentStatus === "Cancelled"} onClick={() => setPaymentJob(row)} className="rounded-lg bg-emerald-600 px-2.5 py-1.5 text-xs font-black text-white disabled:bg-slate-300">Record Payment</button></Cell></tr>)}</WideTable></ReportSection>
    {paymentJob && <PaymentModal kind="invoice" job={paymentJob} settings={settings} onClose={() => setPaymentJob(null)} onSaved={async () => { setPaymentJob(null); await onChanged("Invoice payment recorded with audit history."); }} />}
    {historyOpen && <TransactionHistory table="invoice_payments" kind="invoice" onClose={() => setHistoryOpen(false)} onVoided={onChanged} />}
  </div>;
}

function TechnicianPayments({ jobs, allPendingJobs, settings, onOpenJob, onChanged }) {
  const [view,setView]=useState("All Pending Jobs"); const [paymentJob,setPaymentJob]=useState(null); const [historyOpen,setHistoryOpen]=useState(false);
  const pending=allPendingJobs; const paid=jobs.filter((job)=>lower(job.techPaymentStatus)==="paid"); const cancelled=jobs.filter((job)=>lower(job.techPaymentStatus)==="cancelled");
  const visible=view==="Paid History"?paid:view==="Cancelled Technician Payments"?cancelled:pending; const groups=aggregatePerformance(pending,"technician"); const days=pending.map((job)=>daysSince(job.date));
  return <div className="space-y-4"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><MiniKpi label="Total Amount Owed" value={money(pending.reduce((sum,job)=>sum+job.techLabor,0))} /><MiniKpi label="Pending Jobs" value={number(pending.length)} /><MiniKpi label="Technicians Owed" value={number(new Set(pending.map((job)=>job.technician)).size)} /><MiniKpi label="Missing / Zero Labor" value={number(pending.filter((job)=>!job.techLabor).length)} warning /><MiniKpi label="Oldest Pending" value={days.length?`${Math.max(...days)} days`:"-"} /><MiniKpi label="Average Days" value={days.length?(days.reduce((a,b)=>a+b,0)/days.length).toFixed(1):"-"} /></section><div className="flex flex-wrap gap-2">{["All Pending Jobs","By Technician","Paid History","Cancelled Technician Payments"].map((item)=><button key={item} onClick={()=>setView(item)} className={`rounded-xl px-4 py-2 text-sm font-black ${view===item?"bg-blue-600 text-white":"bg-white text-slate-700"}`}>{item}</button>)}<button onClick={()=>setHistoryOpen(true)} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-black text-white">Transaction History</button></div>
    {view==="By Technician"?<ReportSection title="Amounts Owed by Technician" icon={Users}><WideTable headers={["Technician","Pending Jobs","Tech Labor Owed","Estimated Job Profit"]}>{groups.map((row)=><tr key={row.name} className="border-t"><Cell strong>{row.name}</Cell><Cell>{row.jobs}</Cell><MoneyCell value={row.techLabor} strong/><MoneyCell value={row.estimatedProfit}/></tr>)}</WideTable></ReportSection>:<ReportSection title={view} subtitle={view==="All Pending Jobs"?"Every current pending technician payment in the selected Accounting dataset":"Audited job payment status view"} icon={WalletCards}><WideTable headers={["Job #","Date","Invoice #","Reference #","Company","Technician","Location","Tech Labor","Status","Days Pending","Paid Date","Paid By","Dispatcher","Updates","Actions"]}>{visible.map((job)=><tr key={job.id} className="border-t even:bg-slate-50"><LinkCell label={job.jobNumber} job={job} onOpenJob={onOpenJob}/><Cell>{date(job.date)}</Cell><LinkCell label={job.invoiceNumber||"-"} job={job} onOpenJob={onOpenJob}/><LinkCell label={job.referenceNumber||"-"} job={job} onOpenJob={onOpenJob}/><Cell>{job.company}</Cell><Cell strong>{job.technician||"Unassigned"}</Cell><Cell>{job.location}</Cell><MoneyCell value={job.techLabor} strong/><Cell><Status value={job.techPaymentStatus}/></Cell><Cell>{daysSince(job.date)}</Cell><Cell>{job.techPaymentPaidAt?dateTime(job.techPaymentPaidAt):"-"}</Cell><Cell>{job.techPaymentPaidBy||"-"}</Cell><Cell>{job.dispatcher}</Cell><Cell wide>{job.updates||"-"}</Cell><Cell>{isPendingTechPayment(job)&&<button disabled={!job.techLabor} onClick={()=>setPaymentJob(job)} className="rounded-lg bg-emerald-600 px-2.5 py-1.5 text-xs font-black text-white disabled:bg-slate-300">Record Payment</button>}</Cell></tr>)}</WideTable></ReportSection>}
    {paymentJob&&<PaymentModal kind="technician" job={{...paymentJob,amountPaid:0,balanceDue:paymentJob.techLabor}} settings={settings} onClose={()=>setPaymentJob(null)} onSaved={async()=>{setPaymentJob(null);await onChanged("Technician payment recorded with permanent transaction history.");}}/>}{historyOpen&&<TransactionHistory table="technician_payment_transactions" kind="technician" onClose={()=>setHistoryOpen(false)} onVoided={onChanged}/>}</div>;
}

function Profitability({ jobs, onOpenJob }) { const [dimension,setDimension]=useState("Job"); const rows=useMemo(()=>dimension==="Job"?[...jobs].map((job)=>({name:job.invoiceNumber||job.jobNumber,jobs:1,billed:job.totalBill,parts:job.parts,techLabor:job.techLabor,estimatedProfit:estimatedProfit(job),job})).sort((a,b)=>b.estimatedProfit-a.estimatedProfit):aggregatePerformance(jobs,{Customer:"company",Technician:"technician",Dispatcher:"dispatcher",City:"city","Service Area":"serviceAreaId"}[dimension]),[jobs,dimension]); return <ReportSection title="Profitability" subtitle="Always shown as Estimated Job Profit; company overhead is not stored" icon={BarChart3}><div className="mb-4 flex flex-wrap gap-2">{["Job","Customer","Technician","Dispatcher","City","Service Area"].map((item)=><button key={item} onClick={()=>setDimension(item)} className={`rounded-xl px-4 py-2 text-sm font-black ${dimension===item?"bg-blue-600 text-white":"bg-slate-100 text-slate-700"}`}>{item}</button>)}</div><WideTable headers={[dimension,"Jobs","Total Billed","Parts","Tech Labor","Estimated Job Profit","Profit Margin","Actions"]}>{rows.map((row,index)=><tr key={`${row.name}-${index}`} className={`border-t even:bg-slate-50 ${row.estimatedProfit<0?"bg-red-50":""}`}><Cell strong>{row.name||"Unassigned"}</Cell><Cell>{row.jobs}</Cell><MoneyCell value={row.billed}/><MoneyCell value={row.parts}/><MoneyCell value={row.techLabor}/><MoneyCell value={row.estimatedProfit} strong/><Cell>{percent(row.billed?row.estimatedProfit/row.billed:0)}</Cell><Cell>{row.job&&<button onClick={()=>onOpenJob?.(row.job.id)} className="font-black text-blue-700">Open</button>}</Cell></tr>)}</WideTable></ReportSection>; }

function InternalControl({ jobs, onOpenJob }) { return <ReportSection title="Red Internal Control Queue" subtitle="Every currently red job, independent of all other statuses" icon={ShieldAlert}><WideTable headers={["Job #","Date","Time","Invoice #","Reference #","Company","Technician","Dispatcher","Location","Job Status","Invoice Status","Tech Payment Status","Total Bill","Updates","Days in Queue"]}>{jobs.map((job)=><tr key={job.id} className="border-t border-red-100 bg-red-50/60"><LinkCell label={job.jobNumber} job={job} onOpenJob={onOpenJob}/><Cell>{date(job.date)}</Cell><Cell>{job.time||"-"}</Cell><LinkCell label={job.invoiceNumber||"-"} job={job} onOpenJob={onOpenJob}/><LinkCell label={job.referenceNumber||"-"} job={job} onOpenJob={onOpenJob}/><Cell strong>{job.company}</Cell><Cell>{job.technician}</Cell><Cell>{job.dispatcher}</Cell><Cell>{job.location}</Cell><Cell><Status value={job.status}/></Cell><Cell><Status value={job.invoiceStatus}/></Cell><Cell><Status value={job.techPaymentStatus}/></Cell><MoneyCell value={job.totalBill}/><Cell wide>{job.updates||"-"}</Cell><Cell>{daysSince(job.updatedAt||job.createdAt||job.date)}</Cell></tr>)}</WideTable></ReportSection>; }

function AccountingSettings({ settings, onSaved }) { const [form,setForm]=useState(()=>settingsToForm(settings)); const [saving,setSaving]=useState(false); useEffect(()=>setForm(settingsToForm(settings)),[settings]); async function submit(event){event.preventDefault();setSaving(true);try{const saved=await saveAccountingSettings({default_payment_terms_days:form.defaultTerms===""?null:Number(form.defaultTerms),allowed_payment_methods:form.methods.split(",").map((v)=>v.trim()).filter(Boolean),aging_thresholds:[30,60,90],technician_payment_approval_threshold:form.techThreshold===""?null:Number(form.techThreshold),require_confirmation_number:form.requireConfirmation,require_payment_notes:form.requireNotes,default_report_date_range:form.defaultRange,company_legal_name:form.companyName,accounting_contact_information:form.contact||null,pdf_footer:form.footer,currency:form.currency.toUpperCase()});onSaved(saved);}catch(error){alert(error.message);}finally{setSaving(false)}} return <ReportSection title="Accounting Settings" subtitle="Administrative controls only; no payment credentials are stored" icon={Settings}><form onSubmit={submit} className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Setting label="Default payment terms (days)" value={form.defaultTerms} onChange={(v)=>setForm({...form,defaultTerms:v})} type="number"/><Setting label="Allowed payment methods (comma separated)" value={form.methods} onChange={(v)=>setForm({...form,methods:v})}/><Setting label="Technician approval threshold" value={form.techThreshold} onChange={(v)=>setForm({...form,techThreshold:v})} type="number"/><Setting label="Default report date range" value={form.defaultRange} onChange={(v)=>setForm({...form,defaultRange:v})}/><Setting label="Company legal name" value={form.companyName} onChange={(v)=>setForm({...form,companyName:v})}/><Setting label="Accounting contact information" value={form.contact} onChange={(v)=>setForm({...form,contact:v})}/><Setting label="PDF footer" value={form.footer} onChange={(v)=>setForm({...form,footer:v})}/><Setting label="Currency" value={form.currency} onChange={(v)=>setForm({...form,currency:v})}/><div className="grid gap-2"><Toggle label="Require confirmation number" checked={form.requireConfirmation} onChange={(v)=>setForm({...form,requireConfirmation:v})}/><Toggle label="Require payment notes" checked={form.requireNotes} onChange={(v)=>setForm({...form,requireNotes:v})}/></div><div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-sm font-bold text-blue-900">Financial export permissions are assigned per user in Administration → Users and enforced separately from accounting data access.</div><div className="md:col-span-2 xl:col-span-3"><button disabled={saving} className="rounded-xl bg-blue-600 px-5 py-3 font-black text-white disabled:bg-slate-400">{saving?"Saving...":"Save Accounting Settings"}</button></div></form></ReportSection>; }

function PaymentModal({ kind, job, settings, onClose, onSaved }) { const [form,setForm]=useState({paymentDate:new Date().toISOString().slice(0,10),amount:String(kind==="invoice"?job.balanceDue:job.techLabor),paymentMethod:"",confirmationNumber:"",notes:""}); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const newAmount=numberValue(form.amount); const remaining=Math.max((kind==="invoice"?job.balanceDue:job.techLabor)-newAmount,0); async function submit(event){event.preventDefault();setSaving(true);setError("");try{const values={jobId:job.id,...form};if(kind==="invoice")await recordInvoicePayment(values);else await recordTechnicianPayment(values);await onSaved();}catch(saveError){setError(saveError.message||"Unable to record payment.");}finally{setSaving(false)}} const methods=settings?.allowed_payment_methods||[]; return <Modal title={kind==="invoice"?"Record Customer Payment":"Record Technician Payment"} onClose={onClose}><div className="grid grid-cols-2 gap-3 rounded-2xl bg-slate-50 p-4"><SummaryValue label={kind==="invoice"?"Invoice Total":"Tech Labor"} value={money(kind==="invoice"?job.totalBill:job.techLabor)}/><SummaryValue label="Previously Paid" value={money(kind==="invoice"?job.amountPaid:0)}/><SummaryValue label="New Payment" value={money(newAmount)}/><SummaryValue label="Remaining Balance" value={money(remaining)}/></div><form onSubmit={submit} className="mt-4 grid gap-3"><Setting label="Payment date" type="date" value={form.paymentDate} onChange={(v)=>setForm({...form,paymentDate:v})}/><Setting label="Amount" type="number" value={form.amount} onChange={(v)=>setForm({...form,amount:v})}/><label className="grid gap-1.5 text-sm font-bold text-slate-600">Payment method<select value={form.paymentMethod} onChange={(e)=>setForm({...form,paymentMethod:e.target.value})} className="rounded-xl border px-3 py-2.5"><option value="">Select method</option>{methods.map((item)=><option key={item}>{item}</option>)}</select></label><Setting label={`Confirmation number${settings?.require_confirmation_number?" *":""}`} value={form.confirmationNumber} onChange={(v)=>setForm({...form,confirmationNumber:v})}/><Setting label={`Notes${settings?.require_payment_notes?" *":""}`} value={form.notes} onChange={(v)=>setForm({...form,notes:v})}/>{error&&<p className="font-bold text-red-600">{error}</p>}<button disabled={saving||newAmount<=0} className="rounded-xl bg-emerald-600 px-4 py-3 font-black text-white disabled:bg-slate-400">{saving?"Recording...":"Record Immutable Payment"}</button></form></Modal>; }

function TransactionHistory({ table, kind, onClose, onVoided }) { const [page,setPage]=useState(0); const [data,setData]=useState({rows:[],count:0}); const [loading,setLoading]=useState(true); async function load(){setLoading(true);try{setData(await loadTransactionPage(table,{page,pageSize:50}));}catch(error){alert(error.message);}finally{setLoading(false)}} useEffect(()=>{load()},[page]); async function voidRow(row){const reason=window.prompt("Enter required void reason:");if(!reason)return;try{if(kind==="invoice")await voidInvoicePayment(row.id,reason);else await voidTechnicianPayment(row.id,reason);await load();await onVoided(`${kind==="invoice"?"Invoice":"Technician"} payment voided with audit history.`);}catch(error){alert(error.message)}} return <Modal wide title={`${kind==="invoice"?"Invoice":"Technician"} Payment Transactions`} onClose={onClose}>{loading?<LoadingPanel/>:<><WideTable headers={["Payment Date","Job ID","Amount","Method","Confirmation","Notes","Created","Status","Actions"]}>{data.rows.map((row)=><tr key={row.id} className={`border-t ${row.voided_at?"bg-red-50 text-slate-500":""}`}><Cell>{date(row.payment_date)}</Cell><Cell>{String(row.job_id).slice(0,8)}</Cell><MoneyCell value={row.amount}/><Cell>{row.payment_method||"-"}</Cell><Cell>{row.confirmation_number||"-"}</Cell><Cell>{row.notes||"-"}</Cell><Cell>{dateTime(row.created_at)}</Cell><Cell><Status value={row.voided_at?"Voided":"Active"}/></Cell><Cell>{!row.voided_at&&<button onClick={()=>voidRow(row)} className="font-black text-red-600">Void</button>}</Cell></tr>)}</WideTable><div className="mt-4 flex items-center justify-between"><span className="text-sm font-bold text-slate-500">{data.count} transactions</span><div className="flex gap-2"><button disabled={page===0} onClick={()=>setPage((p)=>p-1)} className="rounded-lg border px-3 py-2 font-bold disabled:opacity-40">Previous</button><button disabled={(page+1)*50>=data.count} onClick={()=>setPage((p)=>p+1)} className="rounded-lg border px-3 py-2 font-bold disabled:opacity-40">Next</button></div></div></>}</Modal>; }

function KpiDrilldown({ label, rows, key: kpiKey, onClose, onOpenJob }) { const total=rows.reduce((sum,job)=>sum+(kpiKey==="partsExpense"?job.parts:kpiKey==="techLaborExpense"||kpiKey==="techPaymentsDue"?job.techLabor:kpiKey==="estimatedProfit"?estimatedProfit(job):job.totalBill),0); return <Modal wide title={`${label} - Reconciliation Detail`} onClose={onClose}><p className="mb-4 rounded-xl bg-blue-50 p-3 text-sm font-bold text-blue-900">{rows.length} matching jobs{kpiKey.includes("Jobs")||["totalJobs","pendingTechPaymentJobs","redInternalControlJobs","openCustomerInvoices","dryRuns"].includes(kpiKey)?"":` · Reconciled total ${money(total)}`}</p><WideTable headers={["Date","Invoice #","Company","Reference #","Status","Invoice Status","Tech Payment","Total Bill","Parts","Tech Labor","Estimated Profit"]}>{rows.map((job)=><tr key={job.id} className="border-t even:bg-slate-50"><Cell>{date(job.date)}</Cell><LinkCell label={job.invoiceNumber||"-"} job={job} onOpenJob={onOpenJob}/><Cell strong>{job.company}</Cell><LinkCell label={job.referenceNumber||"-"} job={job} onOpenJob={onOpenJob}/><Cell><Status value={job.status}/></Cell><Cell><Status value={job.invoiceStatus}/></Cell><Cell><Status value={job.techPaymentStatus}/></Cell><MoneyCell value={job.totalBill}/><MoneyCell value={job.parts}/><MoneyCell value={job.techLabor}/><MoneyCell value={estimatedProfit(job)} strong/></tr>)}</WideTable></Modal>; }

function ReportSection({title,subtitle,icon:Icon,children}){return <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><header className="flex items-center gap-3 border-b border-slate-200 px-5 py-4"><span className="rounded-xl bg-blue-50 p-2 text-blue-700"><Icon className="h-5 w-5"/></span><div><h2 className="text-xl font-black text-slate-950">{title}</h2>{subtitle&&<p className="text-sm font-semibold text-slate-500">{subtitle}</p>}</div></header><div className="p-4 sm:p-5">{children}</div></section>}
function KpiCard({label,value,icon:Icon,tone,onClick}){const tones={blue:"bg-blue-50 text-blue-700",green:"bg-emerald-50 text-emerald-700",red:"bg-red-50 text-red-700",orange:"bg-amber-50 text-amber-700",slate:"bg-slate-100 text-slate-700"};return <button type="button" onClick={onClick} className="group min-h-32 rounded-2xl border border-slate-200 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><span className={`inline-flex rounded-xl p-2 ${tones[tone]}`}><Icon className="h-5 w-5"/></span><p className="mt-3 text-[10px] font-black uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-2xl font-black text-slate-950">{value}</p><p className="mt-1 text-[10px] font-bold text-blue-600 opacity-0 group-hover:opacity-100">View reconciliation</p></button>}
function MiniKpi({label,value,compact,warning}){return <div className={`rounded-2xl border p-4 ${warning?"border-amber-200 bg-amber-50":"border-slate-200 bg-white"}`}><p className="text-[10px] font-black uppercase text-slate-500">{label}</p><p className={`${compact?"text-xl":"text-2xl"} mt-1 font-black text-slate-950`}>{value}</p></div>}
function SummaryPanel({title,rows}){return <div className="rounded-2xl border bg-white p-5"><h3 className="font-black">{title}</h3><div className="mt-3 divide-y">{rows.map(([label,value])=><div key={label} className="flex justify-between py-2 text-sm"><span className="text-slate-500">{label}</span><strong>{value}</strong></div>)}</div></div>}
function BreakdownPanel({title,values}){const total=Object.values(values).reduce((a,b)=>a+b,0);return <div className="rounded-2xl border bg-white p-5"><h3 className="font-black">{title}</h3><div className="mt-3 space-y-3">{Object.entries(values).sort((a,b)=>b[1]-a[1]).map(([label,value])=><div key={label}><div className="mb-1 flex justify-between text-xs font-bold"><span>{label}</span><span>{value}</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-blue-600" style={{width:`${total?value/total*100:0}%`}}/></div></div>)}</div></div>}
function Ranking({title,rows}){return <div className="rounded-2xl border bg-white p-5"><h3 className="font-black">{title}</h3><div className="mt-3 space-y-2">{rows.slice(0,5).map((row,index)=><div key={row.name} className="flex items-center justify-between rounded-xl bg-slate-50 p-2.5"><span className="truncate text-sm font-bold"><b className="mr-2 text-blue-600">#{index+1}</b>{row.name}</span><span className="text-xs font-black">{money(row.billed)}</span></div>)}</div></div>}
function FilterBar({search,setSearch,children}){return <div className="mb-4 grid gap-2 md:grid-cols-2 xl:grid-cols-6"><label className="relative xl:col-span-2"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Search invoice, reference, company..." className="h-10 w-full rounded-xl border pl-9 pr-3 text-sm"/></label>{children}</div>}
function WideTable({headers,children}){return <div className="overflow-x-auto rounded-xl border border-slate-200"><table className="min-w-full whitespace-nowrap text-left text-xs"><thead className="bg-[#0b1f3a] text-white"><tr>{headers.map((header)=><th key={header} className="px-3 py-3 font-black">{header}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Cell({children,strong,wide,warning}){return <td className={`px-3 py-2.5 align-top ${strong?"font-black text-slate-900":"text-slate-600"} ${wide?"max-w-xs whitespace-normal":""} ${warning?"font-black text-amber-700":""}`}>{children}</td>}
function MoneyCell({value,strong}){return <Cell strong={strong}>{money(value)}</Cell>}
function LinkCell({label,job,onOpenJob}){return <td className="px-3 py-2.5"><button onClick={()=>onOpenJob?.(job.id)} className="font-black text-blue-700 hover:underline">{label}</button></td>}
function Status({value}){const key=lower(value);const style=key.includes("paid")||key==="completed"||key==="active"?"bg-emerald-100 text-emerald-800":key.includes("cancel")||key==="voided"?"bg-red-100 text-red-800":key.includes("pending")||key.includes("unpaid")||key.includes("partial")?"bg-amber-100 text-amber-800":key==="overpaid"?"bg-purple-100 text-purple-800":"bg-blue-100 text-blue-800";return <span className={`rounded-full px-2 py-1 text-[10px] font-black ${style}`}>{value||"Unknown"}</span>}
function Modal({title,onClose,children,wide}){return <div className="fixed inset-0 z-[170] flex items-center justify-center bg-slate-950/70 p-3" onMouseDown={onClose}><div role="dialog" aria-modal="true" className={`max-h-[94vh] w-full overflow-y-auto rounded-3xl bg-white p-5 shadow-2xl ${wide?"max-w-[1500px]":"max-w-xl"}`} onMouseDown={(e)=>e.stopPropagation()}><header className="mb-4 flex items-start justify-between gap-3"><h2 className="text-2xl font-black">{title}</h2><button onClick={onClose} className="rounded-xl bg-slate-100 p-2"><X className="h-5 w-5"/></button></header>{children}</div></div>}
function LoadingPanel(){return <div className="flex min-h-64 items-center justify-center rounded-2xl bg-white"><LoaderCircle className="h-8 w-8 animate-spin text-blue-600"/></div>}
function Empty({label}){return <p className="py-6 text-center text-sm font-semibold text-slate-500">{label}</p>}
function Setting({label,value,onChange,type="text"}){return <label className="grid gap-1.5 text-sm font-bold text-slate-600">{label}<input type={type} step={type==="number"?"0.01":undefined} value={value} onChange={(e)=>onChange(e.target.value)} className="rounded-xl border border-slate-300 px-3 py-2.5 text-slate-900"/></label>}
function Toggle({label,checked,onChange}){return <label className="flex items-center gap-3 rounded-xl bg-slate-50 p-3 text-sm font-bold"><input type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)}/>{label}</label>}
function SummaryValue({label,value}){return <div><p className="text-[10px] font-black uppercase text-slate-500">{label}</p><p className="font-black">{value}</p></div>}
function settingsToForm(s){return {defaultTerms:s?.default_payment_terms_days??"",methods:(s?.allowed_payment_methods||[]).join(", "),techThreshold:s?.technician_payment_approval_threshold??"",requireConfirmation:Boolean(s?.require_confirmation_number),requireNotes:Boolean(s?.require_payment_notes),defaultRange:s?.default_report_date_range||"This Month",companyName:s?.company_legal_name||"NTTR - National Truck Trailer Repair",contact:s?.accounting_contact_information||"",footer:s?.pdf_footer||"Confidential - NTTR",currency:s?.currency||"USD"}}
function selectControl(label,value,setValue,values){return <select aria-label={label} value={value} onChange={(e)=>setValue(e.target.value)} className="h-10 rounded-xl border px-2 text-sm font-bold"><option>All</option>{values.filter((v)=>v&&v!=="All").map((item)=><option key={item}>{item}</option>)}</select>}
function unique(rows,key){return ["All",...new Set(rows.map((row)=>row[key]).filter(Boolean))].sort()}
function matches(job,query){const q=lower(query);return !q||[job.invoiceNumber,job.referenceNumber,job.company,job.city,job.dispatcher,job.technician,job.location].some((value)=>lower(value).includes(q))}
function money(value){return moneyFormat.format(numberValue(value))} function number(value){return new Intl.NumberFormat("en-US").format(numberValue(value))} function percent(value){return `${(numberValue(value)*100).toFixed(1)}%`}
function date(value){if(!value)return "-";return new Intl.DateTimeFormat("en-US",{dateStyle:"medium"}).format(new Date(`${String(value).slice(0,10)}T00:00:00`))} function dateTime(value){if(!value)return "-";return new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function daysSince(value){if(!value)return 0;const start=new Date(String(value).length===10?`${value}T00:00:00`:value);return Math.max(0,Math.floor((Date.now()-start.getTime())/86400000))}
function rangeLabel(preset,custom){return preset==="Custom Range"?`${custom.from||"Start"} to ${custom.to||"Today"}`:preset}

function OutstandingSentInvoicesReport({ source, settings, session, onClose, onOpenJob, onChanged }) {
  const [mode,setMode]=useState("All Outstanding"); const [preset,setPreset]=useState("This Month"); const [custom,setCustom]=useState({from:"",to:""}); const [paymentJob,setPaymentJob]=useState(null); const [busy,setBusy]=useState("");
  const rows=useMemo(()=>filterOutstandingInvoices(source.rows,mode==="All Outstanding"?"All Outstanding":preset,custom),[source.rows,mode,preset,custom.from,custom.to]);
  const summary=useMemo(()=>summarizeOutstandingInvoices(rows),[rows]); const filterLabel=mode==="All Outstanding"?"All Outstanding":rangeLabel(preset,custom);
  async function runExport(format){setBusy(format);try{await exportOutstandingInvoices({rows,summary,filterLabel,generatedBy:session?.name||session?.username||"Administrator",footer:settings?.pdf_footer},format);await logAccountingExport("outstanding-sent-invoices",{format,range:filterLabel,invoice_count:summary.invoiceCount,total_outstanding:summary.totalOutstanding});}catch(error){alert(error.message||"Export failed.");}finally{setBusy("")}}
  return <Modal wide title="Outstanding Sent Invoices Report" onClose={onClose}><div className="mb-4 flex flex-col gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 xl:flex-row xl:items-center xl:justify-between"><div><p className="font-black text-amber-950">Sent • Awaiting Customer Payment</p><p className="text-sm font-semibold text-amber-800">Amount due is Total Bill minus non-voided customer payment transactions.</p></div><div className="flex flex-wrap gap-2"><ExportButton label="Export PDF" icon={FileText} busy={busy} onClick={()=>runExport("pdf")}/><ExportButton label="Export Excel" icon={FileSpreadsheet} busy={busy} onClick={()=>runExport("xlsx")}/><ExportButton label="Print" icon={Printer} busy={busy} onClick={()=>runExport("print")}/></div></div>
    <div className="mb-4 flex flex-wrap items-end gap-2"><ModeButton active={mode==="All Outstanding"} onClick={()=>setMode("All Outstanding")}>All Outstanding</ModeButton><ModeButton active={mode==="Current Date Filter"} onClick={()=>setMode("Current Date Filter")}>Current Date Filter</ModeButton>{mode==="Current Date Filter"&&<><select value={preset} onChange={(event)=>setPreset(event.target.value)} className="h-10 rounded-xl border px-3 text-sm font-bold">{OUTSTANDING_DATE_PRESETS.map((value)=><option key={value}>{value}</option>)}</select>{preset==="Custom Range"&&<><Setting label="From" type="date" value={custom.from} onChange={(value)=>setCustom({...custom,from:value})}/><Setting label="To" type="date" value={custom.to} onChange={(value)=>setCustom({...custom,to:value})}/></>}</>}</div>
    <section className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><MiniKpi label="Total Sent / Unpaid Invoices" value={number(summary.invoiceCount)}/><MiniKpi label="Total Outstanding Amount" value={money(summary.totalOutstanding)} warning/><MiniKpi label="Average Invoice" value={money(summary.averageInvoice)}/><MiniKpi label="Oldest Outstanding Invoice" value={summary.oldestOutstanding==null?"Not available":`${summary.oldestOutstanding} days`}/><MiniKpi label="Average Days Outstanding" value={summary.averageDaysOutstanding==null?"Not available":summary.averageDaysOutstanding.toFixed(1)}/></section>
    <WideTable headers={["Invoice #","Date","Company","Reference #","Location","Dispatcher","Technician","Invoice Status","Payment Status","Payment Method","Total Bill","Amount Paid","Amount Due","Days Outstanding","Updates","Actions"]}>{rows.map((row)=><tr key={row.id} className="border-t border-amber-100 even:bg-amber-50/40"><LinkCell label={row.invoiceNumber||"-"} job={row} onOpenJob={onOpenJob}/><Cell>{date(row.date)}</Cell><Cell strong>{row.company||"-"}</Cell><LinkCell label={row.referenceNumber||"-"} job={row} onOpenJob={onOpenJob}/><Cell>{row.location||"-"}</Cell><Cell>{row.dispatcher||"-"}</Cell><Cell>{row.technician||"-"}</Cell><Cell><Status value={row.invoiceStatus}/></Cell><Cell><Status value={row.paymentStatus}/></Cell><Cell>{row.paymentMethod||"-"}</Cell><MoneyCell value={row.totalBill}/><MoneyCell value={row.amountPaid}/><MoneyCell value={row.balanceDue} strong/><Cell>{row.daysOutstanding??"Not available"}</Cell><Cell wide>{row.updates||"-"}</Cell><Cell><div className="flex gap-2"><button onClick={()=>setPaymentJob(row)} className="rounded-lg bg-emerald-600 px-2.5 py-1.5 text-xs font-black text-white">Record Payment</button><button onClick={()=>onOpenJob?.(row.id)} className="font-black text-blue-700">Open</button></div></Cell></tr>)}</WideTable>
    <div className="mt-3 flex justify-end rounded-xl bg-slate-950 px-4 py-3 text-white"><span className="mr-8 font-black">Grand Total</span><span className="font-black text-amber-300">{money(summary.totalOutstanding)}</span></div>{paymentJob&&<PaymentModal kind="invoice" job={paymentJob} settings={settings} onClose={()=>setPaymentJob(null)} onSaved={async()=>{setPaymentJob(null);await onChanged("Invoice payment recorded with audit history.");}}/>}</Modal>;
}

function SmartKpiDrilldown(props){return props.kpiKey==="estimatedProfit"?<ProfitReconciliation rows={props.rows} onClose={props.onClose} onOpenJob={props.onOpenJob}/>:<GenericKpiDrilldown {...props}/>}
function GenericKpiDrilldown({label,rows,kpiKey,onClose,onOpenJob}){const countOnly=kpiKey.includes("Jobs")||["totalJobs","pendingTechPaymentJobs","redInternalControlJobs","openCustomerInvoices","dryRuns"].includes(kpiKey);const total=rows.reduce((sum,job)=>sum+(kpiKey==="partsExpense"?job.parts:kpiKey==="techLaborExpense"||kpiKey==="techPaymentsDue"?job.techLabor:job.totalBill),0);return <Modal wide title={`${label} - Reconciliation Detail`} onClose={onClose}><p className="mb-4 rounded-xl bg-blue-50 p-3 text-sm font-bold text-blue-900">{rows.length} matching jobs{countOnly?"":` · Reconciled total ${money(total)}`}</p><WideTable headers={["Date","Invoice #","Company","Reference #","Status","Invoice Status","Tech Payment","Total Bill","Parts","Tech Labor","Estimated Profit"]}>{rows.map((job)=><tr key={job.id} className="border-t even:bg-slate-50"><Cell>{date(job.date)}</Cell><LinkCell label={job.invoiceNumber||"-"} job={job} onOpenJob={onOpenJob}/><Cell strong>{job.company}</Cell><LinkCell label={job.referenceNumber||"-"} job={job} onOpenJob={onOpenJob}/><Cell><Status value={job.status}/></Cell><Cell><Status value={job.invoiceStatus}/></Cell><Cell><Status value={job.techPaymentStatus}/></Cell><MoneyCell value={job.totalBill}/><MoneyCell value={job.parts}/><MoneyCell value={job.techLabor}/><MoneyCell value={estimatedProfit(job)} strong/></tr>)}</WideTable></Modal>}
function ProfitReconciliation({rows,onClose,onOpenJob}){const r=buildProfitReconciliation(rows);return <Modal wide title="Estimated Profit Reconciliation" onClose={onClose}><p className="mb-4 rounded-xl bg-emerald-50 p-3 text-sm font-black text-emerald-900">Estimated Profit = Total Bill − Parts − Tech Labor. The detailed rows below use this production formula and reconcile exactly to the KPI.</p><section className="mb-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MiniKpi label="Total Billed" value={money(r.totalBilled)}/><MiniKpi label="Total Parts" value={money(r.totalParts)}/><MiniKpi label="Total Tech Labor" value={money(r.totalTechLabor)}/><MiniKpi label="Estimated Profit" value={money(r.estimatedProfit)}/><MiniKpi label="Number of Jobs Included" value={number(r.jobsIncluded)}/><MiniKpi label="Negative-Profit Jobs" value={number(r.negativeProfitJobs)} warning={r.negativeProfitJobs>0}/><MiniKpi label="Jobs with Missing Parts" value={number(r.missingPartsJobs)} warning={r.missingPartsJobs>0}/><MiniKpi label="Jobs with Missing Tech Labor" value={number(r.missingTechLaborJobs)} warning={r.missingTechLaborJobs>0}/></section><WideTable headers={["Job #","Date","Invoice #","Reference #","Company","Technician","Total Bill","Parts","Tech Labor","Estimated Profit","Status"]}>{rows.map((job)=><tr key={job.id} className={`border-t even:bg-slate-50 ${estimatedProfit(job)<0?"bg-red-50":""}`}><LinkCell label={job.jobNumber} job={job} onOpenJob={onOpenJob}/><Cell>{date(job.date)}</Cell><LinkCell label={job.invoiceNumber||"-"} job={job} onOpenJob={onOpenJob}/><LinkCell label={job.referenceNumber||"-"} job={job} onOpenJob={onOpenJob}/><Cell strong>{job.company||"-"}</Cell><Cell>{job.technician||"-"}</Cell><MoneyCell value={job.totalBill}/><MoneyCell value={job.parts}/><MoneyCell value={job.techLabor}/><MoneyCell value={estimatedProfit(job)} strong/><Cell><Status value={job.status}/></Cell></tr>)}</WideTable><div className="mt-3 flex justify-end rounded-xl bg-slate-950 px-4 py-3 text-white"><span className="mr-8 font-black">Reconciled Estimated Profit</span><span className="font-black text-emerald-300">{money(r.estimatedProfit)}</span></div></Modal>}
function OutstandingKpiCard({value,count,onClick}){return <button type="button" onClick={onClick} className="group min-h-32 rounded-2xl border border-amber-300 bg-white p-4 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><span className="inline-flex rounded-xl bg-amber-50 p-2 text-amber-700"><ShieldAlert className="h-5 w-5"/></span><p className="mt-3 text-[10px] font-black uppercase tracking-wide text-slate-500">Outstanding Sent Invoices</p><p className="mt-1 text-2xl font-black text-slate-950">{money(value)}</p><p className="text-xs font-black uppercase text-amber-700">{number(count)} invoices</p><p className="mt-1 text-[10px] font-bold text-amber-700">Sent • Awaiting Customer Payment</p></button>}
function ExportButton({label,icon:Icon,busy,onClick}){return <button onClick={onClick} disabled={Boolean(busy)} className="flex items-center gap-2 rounded-xl bg-white px-3 py-2 text-sm font-black text-slate-800 disabled:opacity-40"><Icon className="h-4 w-4"/>{label}</button>}
function ModeButton({active,onClick,children}){return <button onClick={onClick} className={`rounded-xl px-4 py-2.5 text-sm font-black ${active?"bg-amber-600 text-white":"bg-slate-100 text-slate-700"}`}>{children}</button>}
