import ExcelJS from "exceljs";
import { estimatedProfit, isCancelled, isCompleted, isDryRun, numberValue, profitMargin } from "./accountingData.js";

const C = { navy:"07182D",blue:"163A63",white:"FFFFFF",light:"F1F5F9",lighter:"F8FAFC",silver:"CBD5E1",green:"16A34A",red:"DC2626",orange:"F97316",text:"172033",muted:"64748B" };
const MONEY='$#,##0.00;[Red]($#,##0.00);-'; const PERCENT='0.0%'; const BORDER={style:"thin",color:{argb:"D8E0EA"}};

export async function createAccountingWorkbookBuffer(payload, options={}) {
  const workbook=new ExcelJS.Workbook(); const at=new Date(options.generatedAt||Date.now());
  workbook.creator=options.generatedBy||"NTTR Accounting Center"; workbook.company="NTTR - National Truck Trailer Repair"; workbook.title="NTTR Accounting Center"; workbook.created=at; workbook.modified=at; workbook.calcProperties.fullCalcOnLoad=true;
  const ctx={workbook,payload,options:{...options,generatedAt:at}};
  const id=options.reportId||"complete-workbook";
  if(id==="complete-workbook"||id==="executive-accounting")addExecutive(ctx);
  if(id==="complete-workbook"||id==="customer-invoice-register")addCustomerInvoices(ctx);
  if(id==="complete-workbook"||id==="accounts-receivable")addReceivables(ctx);
  if(id==="complete-workbook"||id==="invoice-payment-history")addInvoiceTransactions(ctx);
  if(id==="complete-workbook"||id==="technician-payments-due")addTechDue(ctx);
  if(id==="complete-workbook"||id==="technician-payment-history")addTechHistory(ctx);
  if(id==="complete-workbook"||id==="profitability")addProfitability(ctx);
  if(id==="complete-workbook"||id==="completed-jobs")addJobRegister(ctx,"Completed Jobs",payload.model.jobs.filter(isCompleted));
  if(id==="complete-workbook"||id==="cancelled-jobs")addJobRegister(ctx,"Cancelled Jobs",payload.model.jobs.filter(isCancelled));
  if(id==="complete-workbook"||id==="dry-runs")addJobRegister(ctx,"Dry Runs",payload.model.jobs.filter(isDryRun));
  if(id==="complete-workbook"||id==="red-internal-control")addInternal(ctx);
  if(id==="complete-workbook")addRaw(ctx);
  return workbook.xlsx.writeBuffer();
}

function base(ctx,name,subtitle,cols){const s=ctx.workbook.addWorksheet(name,{views:[{state:"frozen",ySplit:6,showGridLines:false}],pageSetup:{orientation:"landscape",fitToPage:true,fitToWidth:1,fitToHeight:0,margins:{left:.25,right:.25,top:.6,bottom:.55,header:.2,footer:.25}}});const last=letter(cols);for(let r=1;r<=5;r++)s.mergeCells(`A${r}:${last}${r}`);s.getCell("A1").value="NTTR ACCOUNTING CENTER";s.getCell("A2").value=subtitle;s.getCell("A3").value="NTTR | National Truck Trailer Repair";s.getCell("A4").value=`Generated: ${stamp(ctx.options.generatedAt)} | By: ${ctx.options.generatedBy||"Administrator"} | Filters: ${ctx.options.filterLabel||"All Time"}`;s.getCell("A5").value="Transaction-based accounting | Estimated profit excludes company overhead";[[1,C.navy,20,C.white],[2,C.blue,14,C.white],[3,C.light,10,C.blue],[4,C.lighter,9,C.muted],[5,C.lighter,9,C.muted]].forEach(([r,fill,size,color])=>{const cell=s.getCell(r,1);cell.fill=solid(fill);cell.font={name:"Calibri",size,bold:r<=3,color:{argb:color}};cell.alignment={vertical:"middle",indent:1};s.getRow(r).height=r===1?34:r===2?25:19});s.headerFooter.oddHeader="&LNTTR ACCOUNTING CENTER&CFinancial Operations&R&P of &N";s.headerFooter.oddFooter=`&L${ctx.options.filterLabel||"All Time"}&CConfidential - NTTR&RGenerated ${stamp(ctx.options.generatedAt)}`;s.pageSetup.printTitlesRow="1:6";return s}
function table(s,headers,rows,opts={}){const hr=opts.headerRow||6;s.getRow(hr).values=headers;s.getRow(hr).height=28;s.getRow(hr).eachCell(c=>{c.fill=solid(C.navy);c.font={name:"Calibri",size:10,bold:true,color:{argb:C.white}};c.alignment={horizontal:"center",vertical:"middle",wrapText:true};c.border={top:BORDER,bottom:BORDER,left:BORDER,right:BORDER}});rows.forEach((values,i)=>{const row=s.getRow(hr+i+1);row.values=values.map(value=>value===""?null:value);row.height=opts.wrap?.length?38:20;row.eachCell({includeEmpty:true},(cell,col)=>{cell.font={name:"Calibri",size:10,color:{argb:C.text}};cell.fill=solid(i%2?C.light:C.white);cell.border={bottom:BORDER};cell.alignment={vertical:"middle",horizontal:typeof cell.value==="number"||cell.value?.formula?"right":"left",wrapText:opts.wrap?.includes(col)}});(opts.money||[]).forEach(col=>row.getCell(col).numFmt=MONEY);(opts.percent||[]).forEach(col=>row.getCell(col).numFmt=PERCENT);(opts.dates||[]).forEach(col=>{if(row.getCell(col).value!=null)row.getCell(col).numFmt="mm/dd/yyyy"})});headers.forEach((h,i)=>s.getColumn(i+1).width=Math.min(42,Math.max(10,opts.widths?.[i]||String(h).length+3)));if(rows.length)s.autoFilter={from:{row:hr,column:1},to:{row:hr+rows.length,column:headers.length}};s.pageSetup.printArea=`A1:${letter(headers.length)}${hr+rows.length}`}
function addExecutive(ctx){const s=base(ctx,"Executive Summary","Executive Accounting Report",12);s.views=[{state:"frozen",ySplit:5,showGridLines:false}];const k=ctx.payload.model.kpis;const cards=[["Total Billed",k.totalBilled,"m"],["Parts Expense",k.partsExpense,"m"],["Tech Labor Expense",k.techLaborExpense,"m"],["Estimated Profit",k.estimatedProfit,"m"],["Total Jobs",k.totalJobs],["Completed",k.completedJobs],["Cancelled",k.cancelledJobs],["Dry Runs",k.dryRuns],["Tech Payments Due",k.techPaymentsDue,"m"],["Pending Tech Jobs",k.pendingTechPaymentJobs],["Red Control Jobs",k.redInternalControlJobs],["Open Invoices",k.openCustomerInvoices]];cards.forEach(([label,value,type],i)=>{const r=7+Math.floor(i/4)*3,c=(i%4)*3+1;s.mergeCells(r,c,r,c+2);s.mergeCells(r+1,c,r+2,c+2);const l=s.getCell(r,c),v=s.getCell(r+1,c);l.value=label.toUpperCase();l.fill=solid(C.blue);l.font={name:"Calibri",size:9,bold:true,color:{argb:C.white}};l.alignment={horizontal:"center",vertical:"middle"};v.value=value;v.numFmt=type==="m"?MONEY:"#,##0";v.fill=solid(label.includes("Profit")?"DCFCE7":label.includes("Red")||label.includes("Cancelled")?"FEE2E2":C.lighter);v.font={name:"Calibri",size:17,bold:true,color:{argb:label.includes("Profit")?C.green:C.navy}};v.alignment={horizontal:"center",vertical:"middle"};[l,v].forEach(x=>x.border={top:BORDER,bottom:BORDER,left:BORDER,right:BORDER})});for(let c=1;c<=12;c++)s.getColumn(c).width=14;s.pageSetup.printArea="A1:L15"}
function addCustomerInvoices(ctx){const rows=ctx.payload.model.jobs.map(j=>[j.invoiceNumber,asDate(j.date),j.company,j.referenceNumber,j.location,j.status,j.invoiceStatus,j.paymentMethod,j.totalBill,j.parts,j.techLabor,estimatedProfit(j),j.dispatcher,j.technician,j.updates]);const s=base(ctx,"Customer Invoices","Customer Invoice Register",15);table(s,["Invoice #","Date","Company","Reference #","Location","Job Status","Invoice Status","Payment Method","Total Bill","Parts","Tech Labor","Estimated Profit","Dispatcher","Technician","Updates"],rows,{dates:[2],money:[9,10,11,12],wrap:[15],widths:[16,12,25,16,30,15,16,16,14,14,14,16,20,20,40]})}
function addReceivables(ctx){const rows=ctx.payload.model.receivables.map(j=>[j.invoiceNumber,asDate(j.invoiceDate),asDate(j.invoiceDueDate),j.company,j.referenceNumber,j.totalBill,j.amountPaid,j.balanceDue,j.daysOutstanding??"",j.agingBucket,j.paymentStatus,asDate(j.lastPaymentDate)]);const s=base(ctx,"Accounts Receivable","Transaction-Based Accounts Receivable",12);table(s,["Invoice #","Invoice Date","Due Date","Company","Reference #","Total Bill","Amount Paid","Balance Due","Days Outstanding","Aging Bucket","Payment Status","Last Payment Date"],rows,{dates:[2,3,12],money:[6,7,8],widths:[16,13,13,25,16,14,14,14,15,18,16,15]});conditionalNumber(s,`H7:H${rows.length+6}`,0,C.red,C.green);conditionalText(s,`J7:J${rows.length+6}`,"91+ Days",C.red)}
function addInvoiceTransactions(ctx){const rows=ctx.payload.invoicePayments.map(p=>[p.id,p.job_id,p.invoice_number,asDate(p.payment_date),numberValue(p.amount),p.payment_method,p.confirmation_number,p.notes,p.recorded_by,p.voided_at?"Voided":"Active",asDateTime(p.created_at),asDateTime(p.voided_at),p.void_reason]);const s=base(ctx,"Payment Transactions","Invoice Payment Transactions",13);table(s,["Transaction ID","Job ID","Invoice #","Payment Date","Amount","Method","Confirmation #","Notes","Recorded By","Status","Created At","Voided At","Void Reason"],rows,{dates:[4],money:[5],wrap:[8,13],widths:[38,38,16,14,14,16,20,35,38,12,20,20,30]})}
function addTechDue(ctx){const rows=ctx.payload.pendingTechJobs.map(j=>[j.jobNumber,asDate(j.date),j.invoiceNumber,j.referenceNumber,j.company,j.technician,j.location,j.techLabor,j.techPaymentStatus,ctx.options.generatedAt?days(j.date,ctx.options.generatedAt):0,j.dispatcher,j.updates]);const s=base(ctx,"Technician Payments Due","Every Current Pending Technician Payment",12);table(s,["Job #","Date","Invoice #","Reference #","Company","Technician","Location","Tech Labor","Status","Days Pending","Dispatcher","Updates"],rows,{dates:[2],money:[8],wrap:[12],widths:[12,12,16,16,25,22,30,14,14,14,20,40]})}
function addTechHistory(ctx){const rows=ctx.payload.techTransactions.map(p=>[p.id,p.job_id,p.technician_name,asDate(p.payment_date),numberValue(p.amount),p.payment_method,p.confirmation_number,p.notes,p.created_by,p.voided_at?"Voided":"Active",asDateTime(p.created_at),asDateTime(p.voided_at),p.void_reason]);const s=base(ctx,"Technician Payment History","Transaction-Grade Technician Payment History",13);table(s,["Transaction ID","Job ID","Technician","Payment Date","Amount","Method","Confirmation #","Notes","Created By","Status","Created At","Voided At","Void Reason"],rows,{dates:[4],money:[5],wrap:[8,13],widths:[38,38,22,14,14,16,20,35,38,12,20,20,30]})}
function addProfitability(ctx){const rows=ctx.payload.model.jobs.map((j,i)=>{const r=i+7;return[j.invoiceNumber,j.referenceNumber,j.company,j.technician,j.dispatcher,j.city,j.totalBill,j.parts,j.techLabor,{formula:`G${r}-H${r}-I${r}`,result:estimatedProfit(j)},{formula:`IFERROR(J${r}/G${r},0)`,result:profitMargin(j)}]});const s=base(ctx,"Profitability","Estimated Job Profitability",11);table(s,["Invoice #","Reference #","Customer","Technician","Dispatcher","City","Total Bill","Parts","Tech Labor","Estimated Job Profit","Profit Margin"],rows,{money:[7,8,9,10],percent:[11],widths:[16,16,25,22,20,18,14,14,14,18,14]});conditionalNumber(s,`J7:J${rows.length+6}`,0,C.red,C.green);conditionalNumber(s,`K7:K${rows.length+6}`,0,C.red,C.green)}
function addJobRegister(ctx,name,jobs){const rows=jobs.map(j=>[asDate(j.date),j.invoiceNumber,j.referenceNumber,j.company,j.technician,j.dispatcher,j.status,j.invoiceStatus,j.techPaymentStatus,j.totalBill,j.parts,j.techLabor,estimatedProfit(j),j.location,j.updates]);const s=base(ctx,name,name,15);table(s,["Date","Invoice #","Reference #","Company","Technician","Dispatcher","Job Status","Invoice Status","Tech Payment","Total Bill","Parts","Tech Labor","Estimated Profit","Location","Updates"],rows,{dates:[1],money:[10,11,12,13],wrap:[15],widths:[12,16,16,25,22,20,15,15,15,14,14,14,16,30,40]})}
function addInternal(ctx){const rows=ctx.payload.model.redJobs.map(j=>[j.jobNumber,asDate(j.date),j.time,j.invoiceNumber,j.referenceNumber,j.company,j.technician,j.dispatcher,j.location,j.status,j.invoiceStatus,j.techPaymentStatus,j.totalBill,j.updates,days(j.updatedAt||j.createdAt||j.date,ctx.options.generatedAt)]);const s=base(ctx,"Red Internal Control","Red Internal Control Queue",15);table(s,["Job #","Date","Time","Invoice #","Reference #","Company","Technician","Dispatcher","Location","Job Status","Invoice Status","Tech Payment","Total Bill","Updates","Days in Queue"],rows,{dates:[2],money:[13],wrap:[14],widths:[12,12,10,16,16,25,22,20,30,15,15,15,14,40,14]});for(let r=7;r<rows.length+7;r++)s.getRow(r).eachCell({includeEmpty:true},cell=>{cell.fill=solid("FEE2E2");cell.font={...cell.font,color:{argb:"991B1B"}}})}
function addRaw(ctx){const keys=[...new Set(ctx.payload.model.jobs.flatMap(j=>Object.keys(j.raw||{})))].sort();const rows=ctx.payload.model.jobs.map(j=>keys.map(k=>safe(j.raw?.[k])));const s=base(ctx,"Raw Data","Production Jobs Raw Data",Math.max(keys.length,1));table(s,keys.length?keys:["No columns"],keys.length?rows:[],{widths:keys.map(()=>18)})}
function solid(argb){return{type:"pattern",pattern:"solid",fgColor:{argb}}}function letter(n){let s="";while(n){let m=(n-1)%26;s=String.fromCharCode(65+m)+s;n=Math.floor((n-1)/26)}return s||"A"}function stamp(d){return new Intl.DateTimeFormat("en-US",{dateStyle:"medium",timeStyle:"short"}).format(d)}function asDate(v){if(!v)return"";const d=new Date(`${String(v).slice(0,10)}T00:00:00`);return Number.isNaN(d.getTime())?v:d}function asDateTime(v){if(!v)return"";const d=new Date(v);return Number.isNaN(d.getTime())?v:d}function safe(v){if(v==null)return"";return typeof v==="object"?JSON.stringify(v):v}function days(from,to){const a=new Date(String(from).length===10?`${from}T00:00:00`:from),b=new Date(to);return Number.isNaN(a.getTime())?0:Math.max(0,Math.floor((b-a)/86400000))}
function conditionalNumber(sheet,ref,pivot,negative,positive){sheet.addConditionalFormatting({ref,rules:[{type:"cellIs",operator:"lessThan",formulae:[pivot],style:{font:{color:{argb:negative},bold:true},fill:solid("FEE2E2")}},{type:"cellIs",operator:"greaterThanOrEqual",formulae:[pivot],style:{font:{color:{argb:positive},bold:true},fill:solid("DCFCE7")}}]})}function conditionalText(sheet,ref,value,color){sheet.addConditionalFormatting({ref,rules:[{type:"containsText",operator:"containsText",text:value,style:{font:{color:{argb:color},bold:true},fill:solid("FEE2E2")}}]})}
