-- Add a narrowly scoped Technician Manager role and secure technician lifecycle.

alter table public.app_users drop constraint if exists app_users_role_check;
alter table public.app_users
  add constraint app_users_role_check
  check (lower(role::text) in ('admin', 'dispatcher', 'supervisor', 'technician_manager'));

create or replace function public.can_manage_technicians()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.app_users
    where (auth_user_id = auth.uid() or id = auth.uid())
      and status = 'Active'
      and lower(role::text) in ('admin', 'technician_manager')
  );
$$;

revoke all on function public.can_manage_technicians() from public;
grant execute on function public.can_manage_technicians() to authenticated;

create or replace function public.can_view_active_technicians()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.app_users
    where (auth_user_id = auth.uid() or id = auth.uid())
      and status = 'Active'
      and lower(role::text) in ('admin', 'dispatcher', 'supervisor', 'technician_manager')
  );
$$;

create table if not exists public.technician_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid not null references auth.users(id) on delete restrict,
  actor_email text,
  actor_name text,
  technician_id uuid not null,
  technician_name text not null,
  action text not null check (action in (
    'technician_created',
    'technician_updated',
    'technician_deactivated',
    'technician_deleted',
    'technician_restored'
  )),
  changed_fields jsonb,
  created_at timestamptz not null default now()
);

create index if not exists technician_audit_log_technician_created_idx
  on public.technician_audit_log (technician_id, created_at desc);

alter table public.technician_audit_log enable row level security;
drop policy if exists "technician managers read audit history" on public.technician_audit_log;
create policy "technician managers read audit history"
  on public.technician_audit_log for select
  to authenticated
  using (public.can_manage_technicians());

grant select on public.technician_audit_log to authenticated;
grant usage, select on sequence public.technician_audit_log_id_seq to authenticated;

create or replace function public.write_technician_audit(
  p_technician_id uuid,
  p_technician_name text,
  p_action text,
  p_changed_fields jsonb default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  actor_record public.app_users;
begin
  if not public.can_manage_technicians() then
    raise exception 'Technician management access required';
  end if;

  select * into actor_record
  from public.app_users
  where auth_user_id = auth.uid() or id = auth.uid()
  limit 1;

  insert into public.technician_audit_log (
    actor_user_id, actor_email, actor_name, technician_id,
    technician_name, action, changed_fields
  ) values (
    auth.uid(),
    actor_record.email,
    coalesce(nullif(actor_record.name, ''), nullif(actor_record.username, ''), actor_record.email),
    p_technician_id,
    coalesce(nullif(p_technician_name, ''), 'Technician'),
    p_action,
    p_changed_fields
  );
end;
$$;

create or replace function public.audit_technician_record_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'INSERT' then
    perform public.write_technician_audit(
      new.id, new.full_name, 'technician_created', jsonb_build_object('new', to_jsonb(new))
    );
  elsif old.is_active is not distinct from new.is_active
    and old.deleted_at is not distinct from new.deleted_at
    and old.deleted_by is not distinct from new.deleted_by then
    perform public.write_technician_audit(
      new.id, new.full_name, 'technician_updated',
      jsonb_build_object('before', to_jsonb(old), 'after', to_jsonb(new))
    );
  end if;
  return new;
end;
$$;

drop trigger if exists audit_technician_record_change on public.technicians;
create trigger audit_technician_record_change
after insert or update on public.technicians
for each row execute function public.audit_technician_record_change();

create or replace function public.deactivate_technician(p_technician_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  previous_row public.technicians;
begin
  if not public.can_manage_technicians() then raise exception 'Technician management access required'; end if;
  select * into previous_row from public.technicians where id = p_technician_id for update;
  if not found then raise exception 'Technician not found'; end if;
  if not previous_row.is_active then return; end if;

  update public.technicians
  set is_active = false, deleted_at = now(), deleted_by = auth.uid(),
      status = 'Inactive', availability = 'Offline'
  where id = p_technician_id;

  perform public.write_technician_audit(
    previous_row.id, previous_row.full_name, 'technician_deactivated',
    jsonb_build_object('before', to_jsonb(previous_row))
  );
end;
$$;

create or replace function public.soft_delete_technician(p_technician_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  previous_row public.technicians;
begin
  if not public.can_manage_technicians() then raise exception 'Technician management access required'; end if;
  select * into previous_row from public.technicians where id = p_technician_id for update;
  if not found then raise exception 'Technician not found'; end if;
  if not previous_row.is_active then return; end if;

  update public.technicians
  set is_active = false, deleted_at = now(), deleted_by = auth.uid(),
      status = 'Inactive', availability = 'Offline'
  where id = p_technician_id;

  perform public.write_technician_audit(
    previous_row.id, previous_row.full_name, 'technician_deleted',
    jsonb_build_object('before', to_jsonb(previous_row))
  );
end;
$$;

create or replace function public.restore_technician(p_technician_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  previous_row public.technicians;
begin
  if not public.can_manage_technicians() then raise exception 'Technician management access required'; end if;
  select * into previous_row from public.technicians where id = p_technician_id for update;
  if not found then raise exception 'Technician not found'; end if;

  update public.technicians
  set is_active = true, deleted_at = null, deleted_by = null,
      status = 'Approved', availability = 'Available'
  where id = p_technician_id;

  perform public.write_technician_audit(
    previous_row.id, previous_row.full_name, 'technician_restored',
    jsonb_build_object('before', to_jsonb(previous_row))
  );
end;
$$;

revoke all on function public.write_technician_audit(uuid, text, text, jsonb) from public;
revoke all on function public.deactivate_technician(uuid) from public;
revoke all on function public.soft_delete_technician(uuid) from public;
revoke all on function public.restore_technician(uuid) from public;
grant execute on function public.deactivate_technician(uuid) to authenticated;
grant execute on function public.soft_delete_technician(uuid) to authenticated;
grant execute on function public.restore_technician(uuid) to authenticated;

create or replace function public.protect_technician_lifecycle_fields()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    raise exception 'Permanent technician deletion is disabled';
  end if;
  if (old.is_active is distinct from new.is_active
      or old.deleted_at is distinct from new.deleted_at
      or old.deleted_by is distinct from new.deleted_by)
     and not public.can_manage_technicians() then
    raise exception 'Technician management access required';
  end if;
  return new;
end;
$$;

alter table public.technicians enable row level security;

drop policy if exists "active technicians or admins read technicians" on public.technicians;
drop policy if exists "operational roles read active technicians" on public.technicians;
drop policy if exists "admins read inactive technicians" on public.technicians;
drop policy if exists "admins insert technicians" on public.technicians;
drop policy if exists "only admins may insert technicians" on public.technicians;
drop policy if exists "admins update technicians" on public.technicians;
drop policy if exists "only admins may update technicians" on public.technicians;
drop policy if exists "admins delete technicians" on public.technicians;
drop policy if exists "only admins may delete technicians" on public.technicians;

create policy "operational roles read active technicians"
  on public.technicians for select to authenticated
  using (is_active = true and public.can_view_active_technicians());

create policy "technician managers read all technicians"
  on public.technicians for select to authenticated
  using (public.can_manage_technicians());

create policy "technician managers insert technicians"
  on public.technicians for insert to authenticated
  with check (public.can_manage_technicians());

create policy "technician managers update technicians"
  on public.technicians for update to authenticated
  using (public.can_manage_technicians())
  with check (public.can_manage_technicians());

grant select, insert, update on public.technicians to authenticated;
revoke delete on public.technicians from authenticated;

-- Assignment is intentionally performed separately after resolving Mike by
-- exact app_users.id/auth_user_id/email in the target environment.
