-- Parts Intelligence Center. Prices and availability are configurable estimates only.
create table public.part_categories (id uuid primary key default gen_random_uuid(), name text not null unique, system_name text not null, vehicle_type text not null check(vehicle_type in ('Tractor','53'' Dry Van Trailer','Both')), is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id));
create table public.part_brands (id uuid primary key default gen_random_uuid(), name text not null unique, website_url text, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id));
create table public.parts_catalog (id uuid primary key default gen_random_uuid(), part_name text not null, part_number text not null, description text, category_id uuid not null references public.part_categories(id), brand_id uuid references public.part_brands(id), vehicle_type text not null check(vehicle_type in ('Tractor','53'' Dry Van Trailer','Both')), system_name text not null, estimated_low_price numeric(12,2) not null default 0 check(estimated_low_price>=0), estimated_selling_price numeric(12,2) not null default 0 check(estimated_selling_price>=0), estimated_high_price numeric(12,2) not null default 0 check(estimated_high_price>=estimated_low_price), vendor_cost numeric(12,2) check(vendor_cost>=0), average_cost numeric(12,2) check(average_cost>=0), markup_percent numeric(8,2) check(markup_percent>=0), core_charge numeric(12,2) not null default 0 check(core_charge>=0), unit_of_measure text not null default 'each', availability_status text not null default 'Call to verify' check(availability_status in ('In stock','Limited','Special order','Unavailable','Call to verify')), image_url text, dispatcher_notes text, internal_notes text, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), unique(part_number,brand_id));
create table public.part_cross_references (id uuid primary key default gen_random_uuid(), part_id uuid not null references public.parts_catalog(id) on delete cascade, alternative_part_id uuid references public.parts_catalog(id) on delete cascade, alternate_part_number text not null, brand_name text, notes text, is_verified boolean not null default false, created_at timestamptz not null default now(), unique(part_id,alternate_part_number));
create table public.part_vehicle_compatibility (id uuid primary key default gen_random_uuid(), part_id uuid not null references public.parts_catalog(id) on delete cascade, make text, model text, year_from integer, year_to integer, configuration text, notes text, created_at timestamptz not null default now());
create table public.part_supplier_prices (id uuid primary key default gen_random_uuid(), part_id uuid not null references public.parts_catalog(id) on delete cascade, supplier_name text not null, location_name text, phone text, city text, state text, estimated_price numeric(12,2) check(estimated_price>=0), supplier_discount_percent numeric(8,2), availability text not null default 'Call to verify', last_verified_at timestamptz, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id));
create table public.part_price_history (id bigint generated always as identity primary key, part_id uuid not null references public.parts_catalog(id) on delete cascade, low_price numeric(12,2), selling_price numeric(12,2), high_price numeric(12,2), vendor_cost numeric(12,2), average_cost numeric(12,2), markup_percent numeric(8,2), changed_by uuid references auth.users(id), changed_at timestamptz not null default now());
create table public.part_city_prices (id uuid primary key default gen_random_uuid(), part_id uuid not null references public.parts_catalog(id) on delete cascade, city text not null, state text not null, selling_price numeric(12,2) not null check(selling_price>=0), effective_from date not null default current_date, effective_to date, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(part_id,city,state,effective_from));
create table public.part_inventory_status (id uuid primary key default gen_random_uuid(), part_id uuid not null references public.parts_catalog(id) on delete cascade, supplier_price_id uuid references public.part_supplier_prices(id) on delete cascade, status text not null default 'Call to verify', quantity_available numeric(12,2), last_verified_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.flat_rate_operation_parts (id uuid primary key default gen_random_uuid(), operation_id uuid not null references public.flat_rate_operations(id) on delete cascade, part_id uuid not null references public.parts_catalog(id) on delete cascade, is_required boolean not null default true, default_quantity numeric(8,2) not null default 1 check(default_quantity>0), notes text, created_at timestamptz not null default now(), unique(operation_id,part_id));
create table public.job_parts (id uuid primary key default gen_random_uuid(), job_id uuid not null references public.jobs(id) on delete cascade, part_catalog_id uuid references public.parts_catalog(id) on delete set null, part_name_snapshot text not null, part_number_snapshot text not null, quantity numeric(8,2) not null default 1 check(quantity>0), unit_selling_price numeric(12,2) not null check(unit_selling_price>=0), core_charge numeric(12,2) not null default 0, extended_total numeric(12,2) generated always as (round(quantity*unit_selling_price+core_charge,2)) stored, created_by uuid not null references auth.users(id), created_at timestamptz not null default now());
create table public.estimate_parts (id uuid primary key default gen_random_uuid(), estimate_key text not null, part_catalog_id uuid references public.parts_catalog(id) on delete set null, part_name_snapshot text not null, part_number_snapshot text not null, quantity numeric(8,2) not null default 1, unit_selling_price numeric(12,2) not null, core_charge numeric(12,2) not null default 0, created_by uuid not null references auth.users(id), created_at timestamptz not null default now());
create table public.parts_audit_log (id bigint generated always as identity primary key, table_name text not null, record_id uuid, action text not null, before_data jsonb, after_data jsonb, changed_by uuid references auth.users(id), changed_at timestamptz not null default now());

create index parts_catalog_search_idx on public.parts_catalog(part_name,part_number,vehicle_type,system_name,availability_status); create index part_supplier_location_idx on public.part_supplier_prices(part_id,state,city); create index job_parts_job_idx on public.job_parts(job_id,created_at); create index estimate_parts_key_idx on public.estimate_parts(estimate_key); create index parts_audit_record_idx on public.parts_audit_log(record_id,changed_at desc);

create or replace function public.parts_catalog_dispatcher() returns table(id uuid,part_name text,part_number text,description text,category_id uuid,category_name text,brand_id uuid,brand_name text,vehicle_type text,system_name text,estimated_low_price numeric,estimated_selling_price numeric,estimated_high_price numeric,core_charge numeric,unit_of_measure text,availability_status text,image_url text,dispatcher_notes text,is_active boolean) language sql stable security definer set search_path='' as $$ select p.id,p.part_name,p.part_number,p.description,p.category_id,c.name,p.brand_id,b.name,p.vehicle_type,p.system_name,p.estimated_low_price,p.estimated_selling_price,p.estimated_high_price,p.core_charge,p.unit_of_measure,p.availability_status,p.image_url,p.dispatcher_notes,p.is_active from public.parts_catalog p join public.part_categories c on c.id=p.category_id left join public.part_brands b on b.id=p.brand_id where public.is_active_app_user() and p.is_active $$;
revoke all on function public.parts_catalog_dispatcher() from public; grant execute on function public.parts_catalog_dispatcher() to authenticated;
create or replace function public.part_suppliers_dispatcher(p_part_id uuid) returns table(id uuid,supplier_name text,location_name text,phone text,city text,state text,estimated_price numeric,availability text,last_verified_at timestamptz) language sql stable security definer set search_path='' as $$ select s.id,s.supplier_name,s.location_name,s.phone,s.city,s.state,s.estimated_price,s.availability,s.last_verified_at from public.part_supplier_prices s where public.is_active_app_user() and s.part_id=p_part_id $$;
grant execute on function public.part_suppliers_dispatcher(uuid) to authenticated;

create or replace function public.parts_audit_trigger() returns trigger language plpgsql security definer set search_path='' as $$ declare b jsonb; a jsonb; act text; rid uuid; begin b=case when tg_op='INSERT' then null else to_jsonb(old) end; a=case when tg_op='DELETE' then null else to_jsonb(new) end; rid=coalesce((a->>'id')::uuid,(b->>'id')::uuid); act=case when tg_op='UPDATE' and b->>'is_active'='true' and a->>'is_active'='false' then 'deactivation' when tg_op='UPDATE' and (b->>'estimated_selling_price' is distinct from a->>'estimated_selling_price') then 'price_change' when tg_op='UPDATE' and (b->>'vendor_cost' is distinct from a->>'vendor_cost') then 'cost_change' when tg_op='UPDATE' and (b->>'markup_percent' is distinct from a->>'markup_percent') then 'markup_change' else lower(tg_op) end; insert into public.parts_audit_log(table_name,record_id,action,before_data,after_data,changed_by) values(tg_table_name,rid,act,b,a,auth.uid()); if tg_op='DELETE' then return old; end if; if a ? 'updated_at' then new.updated_at=now(); end if; if tg_table_name='parts_catalog' and tg_op='UPDATE' and (old.estimated_selling_price is distinct from new.estimated_selling_price or old.vendor_cost is distinct from new.vendor_cost or old.markup_percent is distinct from new.markup_percent) then insert into public.part_price_history(part_id,low_price,selling_price,high_price,vendor_cost,average_cost,markup_percent,changed_by) values(new.id,new.estimated_low_price,new.estimated_selling_price,new.estimated_high_price,new.vendor_cost,new.average_cost,new.markup_percent,auth.uid()); end if; return new; end $$;
do $$ declare t text; begin foreach t in array array['parts_catalog','part_categories','part_brands','part_supplier_prices','part_city_prices','part_cross_references'] loop execute format('create trigger %I before insert or update or delete on public.%I for each row execute function public.parts_audit_trigger()',t||'_audit',t); end loop; end $$;

do $$ declare t text; begin foreach t in array array['part_categories','part_brands','parts_catalog','part_cross_references','part_vehicle_compatibility','part_supplier_prices','part_price_history','part_city_prices','part_inventory_status','flat_rate_operation_parts','job_parts','estimate_parts','parts_audit_log'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy "admin manage %s" on public.%I for all to authenticated using(public.is_app_admin()) with check(public.is_app_admin())',t,t); end loop; end $$;
create policy "active read categories" on public.part_categories for select to authenticated using(public.is_active_app_user()); create policy "active read brands" on public.part_brands for select to authenticated using(public.is_active_app_user()); create policy "active read cross refs" on public.part_cross_references for select to authenticated using(public.is_active_app_user()); create policy "active read compatibility" on public.part_vehicle_compatibility for select to authenticated using(public.is_active_app_user()); create policy "active read operation parts" on public.flat_rate_operation_parts for select to authenticated using(public.is_active_app_user()); create policy "active read job parts" on public.job_parts for select to authenticated using(public.is_active_app_user()); create policy "active add job parts" on public.job_parts for insert to authenticated with check(public.is_active_app_user() and created_by=auth.uid()); create policy "active read estimate parts" on public.estimate_parts for select to authenticated using(public.is_active_app_user()); create policy "active add estimate parts" on public.estimate_parts for insert to authenticated with check(public.is_active_app_user() and created_by=auth.uid());

insert into public.part_brands(name) values ('Bendix'),('Meritor'),('Fleetguard'),('Donaldson'),('Phillips'),('SAF-Holland'),('Stemco'),('Generic/OEM Equivalent');
insert into public.part_categories(name,system_name,vehicle_type) values ('Air Brake Components','Brakes','Both'),('Suspension Components','Suspension','Both'),('Wheel End','Wheel End','Both'),('Electrical & Lighting','Electrical','Both'),('Landing Gear','Landing Gear','53'' Dry Van Trailer'),('Door Hardware','Doors','53'' Dry Van Trailer'),('Cooling Components','Cooling','Tractor'),('Engine Service','Engine','Tractor'),('Aftertreatment','Aftertreatment','Tractor'),('Drivetrain','Drivetrain','Tractor');
insert into public.parts_catalog(part_name,part_number,description,category_id,brand_id,vehicle_type,system_name,estimated_low_price,estimated_selling_price,estimated_high_price,vendor_cost,markup_percent,core_charge,availability_status,dispatcher_notes)
select n,pn,d,c.id,b.id,v,s,lo,sell,hi,cost,markup,core,'Call to verify','Estimated customer price; verify fitment, supplier price, freight, tax, and availability before authorization.' from (values
('Type 30/30 Brake Chamber','K065544','Spring brake chamber','Air Brake Components','Bendix','Both','Brakes',85,149,225,72,107,0),('Air Dryer Cartridge','AD9-CART','Desiccant cartridge','Air Brake Components','Bendix','Tractor','Air',45,89,145,39,128,0),('Suspension Air Spring','AS9780','Rolling-lobe air spring','Suspension Components','Generic/OEM Equivalent','Both','Suspension',125,219,340,110,99,0),('Wheel Seal','370003A','Hub wheel seal','Wheel End','Stemco','Both','Wheel End',42,79,125,33,139,0),('LED Stop/Turn Lamp','STT-LED-4','Four-inch sealed LED lamp','Electrical & Lighting','Phillips','53'' Dry Van Trailer','Electrical',18,39,68,14,179,0),('Landing Gear Crank Handle','LG-HANDLE','Replacement crank assembly','Landing Gear','SAF-Holland','53'' Dry Van Trailer','Landing Gear',65,119,190,52,129,0),('Rear Door Hinge','DV-HINGE','Dry van rear door hinge','Door Hardware','Generic/OEM Equivalent','53'' Dry Van Trailer','Doors',28,59,95,24,146,0),('Engine Coolant Pump','WP-ISX15','Heavy-duty coolant pump','Cooling Components','Generic/OEM Equivalent','Tractor','Cooling',325,549,780,280,96,75),('Engine Oil Filter','LF14000NN','Lube filter','Engine Service','Fleetguard','Tractor','Engine',38,69,105,31,123,0),('Diesel Particulate Filter','DPF-ISX','Remanufactured DPF','Aftertreatment','Generic/OEM Equivalent','Tractor','Aftertreatment',1450,2295,3200,1250,84,450),('Clutch Assembly','CLUTCH-15.5','15.5 inch clutch kit','Drivetrain','Generic/OEM Equivalent','Tractor','Drivetrain',850,1395,1900,720,94,100)) x(n,pn,d,cat,brand,v,s,lo,sell,hi,cost,markup,core) join public.part_categories c on c.name=x.cat join public.part_brands b on b.name=x.brand;
