-- Interactive Flat Rate Guide. Labor times are configurable estimates, not guarantees.
create or replace function public.is_app_admin() returns boolean language sql stable security definer set search_path='' as $$
  select exists(select 1 from public.app_users where (auth_user_id=auth.uid() or id=auth.uid()) and status='Active' and role='admin');
$$;
grant execute on function public.is_app_admin() to authenticated;

create table public.flat_rate_categories (
 id uuid primary key default gen_random_uuid(), vehicle_type text not null check(vehicle_type in ('Tractor','53'' Dry Van Trailer')), name text not null, description text, sort_order integer not null default 0, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), unique(vehicle_type,name)
);
create table public.flat_rate_operations (
 id uuid primary key default gen_random_uuid(), vehicle_type text not null check(vehicle_type in ('Tractor','53'' Dry Van Trailer')), category_id uuid not null references public.flat_rate_categories(id), component_name text not null, operation_name text not null, operation_type text not null check(operation_type in ('inspect','diagnose','repair','replace','adjust')), minimum_hours numeric(7,2) not null check(minimum_hours>=0), standard_hours numeric(7,2) not null check(standard_hours>=minimum_hours), maximum_hours numeric(7,2) not null check(maximum_hours>=standard_hours), difficulty text not null default 'Moderate', description text, common_symptoms text, common_replacement_parts text, tools_required text, technical_notes text, image_url text, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id)
);
create table public.flat_rate_parts (id uuid primary key default gen_random_uuid(), operation_id uuid not null references public.flat_rate_operations(id) on delete cascade, part_name text not null, part_number text, quantity numeric(8,2) not null default 1, estimated_unit_cost numeric(12,2), is_optional boolean not null default false, created_at timestamptz not null default now());
create table public.flat_rate_tools (id uuid primary key default gen_random_uuid(), operation_id uuid not null references public.flat_rate_operations(id) on delete cascade, tool_name text not null, is_specialty_tool boolean not null default false, notes text, created_at timestamptz not null default now());
create table public.labor_rate_settings (id uuid primary key default gen_random_uuid(), tractor_rate numeric(12,2) not null default 145, trailer_rate numeric(12,2) not null default 135, diagnostic_rate numeric(12,2) not null default 155, after_hours_rate numeric(12,2) not null default 75, weekend_rate numeric(12,2) not null default 75, holiday_rate numeric(12,2) not null default 125, minimum_labor_hours numeric(7,2) not null default 1, service_call_rate numeric(12,2) not null default 95, mileage_rate numeric(12,2) not null default 2.25, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id));
create table public.city_labor_rates (id uuid primary key default gen_random_uuid(), city text not null, state text not null, tractor_rate numeric(12,2), trailer_rate numeric(12,2), diagnostic_rate numeric(12,2), effective_from date not null default current_date, effective_to date, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id), unique(city,state,effective_from));
create table public.job_labor_operations (id uuid primary key default gen_random_uuid(), job_id uuid not null references public.jobs(id) on delete cascade, flat_rate_operation_id uuid references public.flat_rate_operations(id) on delete set null, operation_name text not null, hours_type text not null check(hours_type in ('minimum','standard','maximum','custom')), hours numeric(8,2) not null check(hours>=0), quantity numeric(8,2) not null default 1 check(quantity>0), labor_rate numeric(12,2) not null check(labor_rate>=0), labor_total numeric(12,2) generated always as (round(hours*labor_rate,2)) stored, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), created_by uuid references auth.users(id), updated_by uuid references auth.users(id));
create table public.flat_rate_audit_log (id bigint generated always as identity primary key, table_name text not null, record_id uuid, action text not null, old_data jsonb, new_data jsonb, changed_fields text[], changed_by uuid references auth.users(id), changed_at timestamptz not null default now());

create index on public.flat_rate_operations(vehicle_type,category_id,operation_type,is_active); create index on public.flat_rate_operations using gin(to_tsvector('english',coalesce(operation_name,'')||' '||coalesce(component_name,'')||' '||coalesce(description,''))); create index on public.job_labor_operations(job_id,created_at desc); create index on public.flat_rate_audit_log(record_id,changed_at desc);

create or replace function public.flat_rate_touch_audit() returns trigger language plpgsql security definer set search_path='' as $$
declare rid uuid; act text; oldj jsonb; newj jsonb;
begin
 oldj=case when tg_op='INSERT' then null else to_jsonb(old) end; newj=case when tg_op='DELETE' then null else to_jsonb(new) end; rid=coalesce((newj->>'id')::uuid,(oldj->>'id')::uuid);
 act=case when tg_op='UPDATE' and oldj->>'is_active'='true' and newj->>'is_active'='false' then 'deactivate' when tg_op='UPDATE' and (oldj ? 'tractor_rate') then 'price_change' else lower(tg_op) end;
 insert into public.flat_rate_audit_log(table_name,record_id,action,old_data,new_data,changed_by) values(tg_table_name,rid,act,oldj,newj,auth.uid());
 if tg_op='DELETE' then return old; end if; new.updated_at=now(); new.updated_by=coalesce(auth.uid(),new.updated_by); return new;
end $$;
do $$ declare t text; begin foreach t in array array['flat_rate_categories','flat_rate_operations','labor_rate_settings','city_labor_rates','job_labor_operations'] loop execute format('create trigger %I before insert or update or delete on public.%I for each row execute function public.flat_rate_touch_audit()',t||'_audit',t); end loop; end $$;

do $$ declare t text; begin foreach t in array array['flat_rate_categories','flat_rate_operations','flat_rate_parts','flat_rate_tools','labor_rate_settings','city_labor_rates','job_labor_operations','flat_rate_audit_log'] loop execute format('alter table public.%I enable row level security',t); end loop; end $$;
create policy "active read categories" on public.flat_rate_categories for select to authenticated using(public.is_active_app_user()); create policy "admin manage categories" on public.flat_rate_categories for all to authenticated using(public.is_app_admin()) with check(public.is_app_admin());
create policy "active read operations" on public.flat_rate_operations for select to authenticated using(public.is_active_app_user()); create policy "admin manage operations" on public.flat_rate_operations for all to authenticated using(public.is_app_admin()) with check(public.is_app_admin());
create policy "active read parts" on public.flat_rate_parts for select to authenticated using(public.is_active_app_user()); create policy "admin manage parts" on public.flat_rate_parts for all to authenticated using(public.is_app_admin()) with check(public.is_app_admin());
create policy "active read tools" on public.flat_rate_tools for select to authenticated using(public.is_active_app_user()); create policy "admin manage tools" on public.flat_rate_tools for all to authenticated using(public.is_app_admin()) with check(public.is_app_admin());
create policy "active read rates" on public.labor_rate_settings for select to authenticated using(public.is_active_app_user()); create policy "admin manage rates" on public.labor_rate_settings for all to authenticated using(public.is_app_admin()) with check(public.is_app_admin());
create policy "active read city rates" on public.city_labor_rates for select to authenticated using(public.is_active_app_user()); create policy "admin manage city rates" on public.city_labor_rates for all to authenticated using(public.is_app_admin()) with check(public.is_app_admin());
create policy "active read job labor" on public.job_labor_operations for select to authenticated using(public.is_active_app_user()); create policy "active add job labor" on public.job_labor_operations for insert to authenticated with check(public.is_active_app_user() and created_by=auth.uid()); create policy "active update job labor" on public.job_labor_operations for update to authenticated using(public.is_active_app_user()) with check(public.is_active_app_user()); create policy "admin delete job labor" on public.job_labor_operations for delete to authenticated using(public.is_app_admin());
create policy "admin read audit" on public.flat_rate_audit_log for select to authenticated using(public.is_app_admin());

insert into public.flat_rate_categories(vehicle_type,name,sort_order) values ('Tractor','Engine',10),('Tractor','Cooling',20),('Tractor','Electrical',30),('Tractor','Air & Brakes',40),('53'' Dry Van Trailer','Brakes',10),('53'' Dry Van Trailer','Doors',20),('53'' Dry Van Trailer','Suspension',30),('53'' Dry Van Trailer','Electrical',40);
insert into public.flat_rate_operations(vehicle_type,category_id,component_name,operation_name,operation_type,minimum_hours,standard_hours,maximum_hours,difficulty,description,common_symptoms,common_replacement_parts,tools_required,technical_notes)
select v,c.id,comp,op,typ,minh,stdh,maxh,diff,descr,sym,parts,tools,'Configurable estimate; inspect vehicle conditions before authorizing work.' from (values
('Tractor','Engine','Engine oil system','Engine oil and filter service','replace',1.0,1.5,2.0,'Routine','Drain oil and replace engine oil filters.','Oil service due; contaminated oil','Oil, oil filters','Drain pan, filter wrench, torque wrench'),
('Tractor','Cooling','Radiator','Replace radiator','replace',4.0,6.0,9.0,'Advanced','Remove and replace radiator; refill and pressure test.','Coolant leak; overheating','Radiator, coolant, hoses','Cooling pressure tester, hand tools'),
('Tractor','Electrical','Starting batteries','Replace battery bank','replace',1.0,1.5,2.5,'Moderate','Test and replace starting batteries.','Slow crank; no start','Batteries, terminal protectant','Multimeter, battery tester'),
('Tractor','Air & Brakes','Air compressor system','Diagnose slow air build','diagnose',1.0,2.0,4.0,'Advanced','Leak test and evaluate compressor, governor, and dryer.','Slow pressure rise; air warning','Air fittings, governor, dryer cartridge','Pressure gauge, leak detector'),
('53'' Dry Van Trailer','Brakes','Brake chamber','Replace brake chamber','replace',1.0,1.5,2.5,'Advanced','Cage spring brake and replace chamber.','Air leak; brake drag','Brake chamber, fittings','Caging bolt, line wrenches'),
('53'' Dry Van Trailer','Doors','Rear swing door','Adjust rear door and hardware','adjust',1.0,2.0,3.5,'Moderate','Align door, hinges, rods, and latches.','Door binds; will not latch','Hinges, rollers, latch hardware','Hand tools, alignment bar'),
('53'' Dry Van Trailer','Suspension','Air spring','Replace suspension air spring','replace',1.0,1.5,2.5,'Moderate','Depressurize suspension and replace air spring.','Trailer leaning; air leak','Air spring, fittings','Jack stands, torque wrench'),
('53'' Dry Van Trailer','Electrical','Lighting circuit','Diagnose trailer lighting','diagnose',0.5,1.0,2.0,'Moderate','Test seven-way power, grounds, harness, and lamps.','Intermittent or inoperative lamps','Lamp, pigtail, wiring repair','Multimeter, test light')) x(v,cat,comp,op,typ,minh,stdh,maxh,diff,descr,sym,parts,tools) join public.flat_rate_categories c on c.vehicle_type=x.v and c.name=x.cat;
insert into public.labor_rate_settings default values;
