-- Secure technician lifecycle management with historical job protection.

alter table public.technicians
  add column if not exists is_active boolean not null default true,
  add column if not exists deleted_at timestamptz,
  add column if not exists deleted_by uuid references auth.users(id) on delete set null;

create index if not exists idx_technicians_is_active
  on public.technicians (is_active);

update public.technicians
set is_active = false,
    deleted_at = coalesce(deleted_at, now()),
    availability = 'Offline'
where lower(coalesce(status, '')) = 'inactive' and is_active;

create table if not exists public.technician_deletion_audit (
  id bigint generated by default as identity primary key,
  technician_id uuid not null,
  technician_name text not null,
  action text not null check (action in ('deactivated', 'restored', 'permanently deleted')),
  admin_user uuid not null references auth.users(id),
  changed_at timestamptz not null default now(),
  previous_values jsonb not null
);

create index if not exists idx_technician_deletion_audit_technician
  on public.technician_deletion_audit (technician_id, changed_at desc);

alter table public.technician_deletion_audit enable row level security;

drop policy if exists "admins read technician deletion audit" on public.technician_deletion_audit;
create policy "admins read technician deletion audit"
  on public.technician_deletion_audit for select
  to authenticated
  using (public.is_active_admin());

-- Inactive technicians are visible only to admins. This restrictive policy
-- composes with the existing active-user policy.
drop policy if exists "active technicians or admins read technicians" on public.technicians;
create policy "active technicians or admins read technicians"
  on public.technicians as restrictive for select
  to authenticated
  using (is_active or public.is_active_admin());

create or replace function public.protect_technician_lifecycle_fields()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' and not public.is_active_admin() then
    raise exception 'Admin access required';
  end if;

  if tg_op = 'UPDATE'
     and (old.is_active is distinct from new.is_active
       or old.deleted_at is distinct from new.deleted_at
       or old.deleted_by is distinct from new.deleted_by)
     and not public.is_active_admin() then
    raise exception 'Admin access required';
  end if;

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

drop trigger if exists protect_technician_lifecycle_fields on public.technicians;
create trigger protect_technician_lifecycle_fields
before update or delete on public.technicians
for each row execute function public.protect_technician_lifecycle_fields();

create or replace function public.deactivate_technician(p_technician_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  previous_row public.technicians;
begin
  if not public.is_active_admin() then raise exception 'Admin access required'; end if;

  select * into previous_row
  from public.technicians
  where id = p_technician_id
  for update;

  if not found then raise exception 'Technician not found'; end if;

  insert into public.technician_deletion_audit
    (technician_id, technician_name, action, admin_user, previous_values)
  values
    (previous_row.id, coalesce(previous_row.full_name, 'Technician'), 'deactivated', auth.uid(), to_jsonb(previous_row));

  update public.technicians
  set is_active = false,
      deleted_at = now(),
      deleted_by = auth.uid(),
      status = 'Inactive',
      availability = 'Offline'
  where id = p_technician_id;
end;
$$;

create or replace function public.restore_technician(p_technician_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  previous_row public.technicians;
  restored_status text;
  restored_availability text;
begin
  if not public.is_active_admin() then raise exception 'Admin access required'; end if;

  select * into previous_row
  from public.technicians
  where id = p_technician_id
  for update;

  if not found then raise exception 'Technician not found'; end if;

  select
    nullif(previous_values->>'status', ''),
    nullif(previous_values->>'availability', '')
  into restored_status, restored_availability
  from public.technician_deletion_audit
  where technician_id = p_technician_id and action = 'deactivated'
  order by changed_at desc
  limit 1;

  insert into public.technician_deletion_audit
    (technician_id, technician_name, action, admin_user, previous_values)
  values
    (previous_row.id, coalesce(previous_row.full_name, 'Technician'), 'restored', auth.uid(), to_jsonb(previous_row));

  update public.technicians
  set is_active = true,
      deleted_at = null,
      deleted_by = null,
      status = coalesce(restored_status, 'Approved'),
      availability = coalesce(restored_availability, 'Available')
  where id = p_technician_id;
end;
$$;

create or replace function public.permanently_delete_unused_technician(p_technician_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  previous_row public.technicians;
begin
  if not public.is_active_admin() then raise exception 'Admin access required'; end if;

  select * into previous_row
  from public.technicians
  where id = p_technician_id
  for update;

  if not found then raise exception 'Technician not found'; end if;

  if previous_row.is_active then
    raise exception 'Deactivate the technician before permanent deletion';
  end if;

  if exists (
    select 1 from public.jobs
    where technician_id = p_technician_id
       or lower(trim(coalesce(tech, ''))) = lower(trim(coalesce(previous_row.full_name, '')))
  ) then
    raise exception 'Permanent deletion blocked: technician is linked to existing jobs';
  end if;

  insert into public.technician_deletion_audit
    (technician_id, technician_name, action, admin_user, previous_values)
  values
    (previous_row.id, coalesce(previous_row.full_name, 'Technician'), 'permanently deleted', auth.uid(), to_jsonb(previous_row));

  delete from public.technicians where id = p_technician_id;
end;
$$;

revoke all on function public.deactivate_technician(uuid) from public;
revoke all on function public.restore_technician(uuid) from public;
revoke all on function public.permanently_delete_unused_technician(uuid) from public;
grant execute on function public.deactivate_technician(uuid) to authenticated;
grant execute on function public.restore_technician(uuid) to authenticated;
grant execute on function public.permanently_delete_unused_technician(uuid) to authenticated;
