-- Sprint 3 - NTTR Fleet Operations Platform database architecture
-- This migration adds technician CRM support tables without changing the existing technicians table.

create table if not exists public.technician_documents (
  id bigint generated by default as identity primary key,
  technician_id uuid not null references public.technicians(id) on delete cascade,
  document_type text not null,
  file_url text not null,
  expiration_date date,
  status text not null default 'pending',
  uploaded_at timestamptz not null default now(),
  constraint technician_documents_status_check
    check (status in ('pending', 'approved', 'rejected', 'expired', 'missing')),
  constraint technician_documents_type_check
    check (document_type in ('driver_license', 'w9', 'insurance', 'agreement', 'other'))
);

create table if not exists public.technician_services (
  id bigint generated by default as identity primary key,
  technician_id uuid not null references public.technicians(id) on delete cascade,
  service_name text not null,
  created_at timestamptz not null default now(),
  constraint technician_services_unique unique (technician_id, service_name)
);

create table if not exists public.technician_coverage (
  id bigint generated by default as identity primary key,
  technician_id uuid not null references public.technicians(id) on delete cascade,
  city text not null,
  state text not null,
  zip_code text,
  service_radius_miles integer not null default 50,
  created_at timestamptz not null default now(),
  constraint technician_coverage_radius_check check (service_radius_miles > 0)
);

create table if not exists public.technician_ratings (
  id bigint generated by default as identity primary key,
  technician_id uuid not null references public.technicians(id) on delete cascade,
  job_id uuid references public.jobs(id) on delete set null,
  rating numeric(3, 2) not null,
  communication_rating numeric(3, 2),
  arrival_rating numeric(3, 2),
  quality_rating numeric(3, 2),
  professionalism_rating numeric(3, 2),
  comments text,
  created_at timestamptz not null default now(),
  constraint technician_ratings_rating_check check (rating >= 1 and rating <= 5),
  constraint technician_ratings_communication_check
    check (communication_rating is null or (communication_rating >= 1 and communication_rating <= 5)),
  constraint technician_ratings_arrival_check
    check (arrival_rating is null or (arrival_rating >= 1 and arrival_rating <= 5)),
  constraint technician_ratings_quality_check
    check (quality_rating is null or (quality_rating >= 1 and quality_rating <= 5)),
  constraint technician_ratings_professionalism_check
    check (professionalism_rating is null or (professionalism_rating >= 1 and professionalism_rating <= 5))
);

create table if not exists public.technician_payments (
  id bigint generated by default as identity primary key,
  technician_id uuid not null references public.technicians(id) on delete cascade,
  job_id uuid references public.jobs(id) on delete set null,
  amount numeric(12, 2) not null default 0,
  payment_method text,
  payment_status text not null default 'pending',
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  constraint technician_payments_amount_check check (amount >= 0),
  constraint technician_payments_status_check
    check (payment_status in ('pending', 'approved', 'paid', 'failed', 'void'))
);

create table if not exists public.technician_invitations (
  id bigint generated by default as identity primary key,
  invite_code text not null unique,
  invited_by text,
  technician_id uuid references public.technicians(id) on delete set null,
  technician_name text,
  phone text,
  email text,
  notes text,
  status text not null default 'Pending',
  expires_at timestamptz,
  opened_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  constraint technician_invitations_status_check
    check (status in ('Pending', 'Opened', 'Completed', 'Expired', 'Cancelled'))
);

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  entity_type text not null,
  entity_id uuid,
  action text not null,
  description text,
  created_by text,
  created_at timestamptz not null default now()
);

create index if not exists idx_technician_documents_technician_id
  on public.technician_documents (technician_id);

create index if not exists idx_technician_documents_type_status
  on public.technician_documents (document_type, status);

create index if not exists idx_technician_documents_expiration_date
  on public.technician_documents (expiration_date);

create index if not exists idx_technician_services_technician_id
  on public.technician_services (technician_id);

create index if not exists idx_technician_services_service_name
  on public.technician_services (service_name);

create index if not exists idx_technician_coverage_technician_id
  on public.technician_coverage (technician_id);

create index if not exists idx_technician_coverage_location
  on public.technician_coverage (state, city, zip_code);

create index if not exists idx_technician_ratings_technician_id
  on public.technician_ratings (technician_id);

create index if not exists idx_technician_ratings_job_id
  on public.technician_ratings (job_id);

create index if not exists idx_technician_ratings_created_at
  on public.technician_ratings (created_at desc);

create index if not exists idx_technician_payments_technician_id
  on public.technician_payments (technician_id);

create index if not exists idx_technician_payments_job_id
  on public.technician_payments (job_id);

create index if not exists idx_technician_payments_status_paid_at
  on public.technician_payments (payment_status, paid_at);

create index if not exists idx_technician_invitations_invite_code
  on public.technician_invitations (invite_code);

create index if not exists idx_technician_invitations_technician_id
  on public.technician_invitations (technician_id);

create index if not exists idx_technician_invitations_status
  on public.technician_invitations (status);

create index if not exists idx_activity_log_entity
  on public.activity_log (entity_type, entity_id);

create index if not exists idx_activity_log_created_at
  on public.activity_log (created_at desc);

create index if not exists idx_activity_log_created_by
  on public.activity_log (created_by);
