-- Hybrid catalog workflow: controlled imports, requests, pricing rules, and richer operation links.
create table public.parts_import_batches (
 id uuid primary key default gen_random_uuid(), file_name text not null, file_type text not null check(file_type in ('csv','xlsx')), duplicate_strategy text not null check(duplicate_strategy in ('skip','update','create')), status text not null default 'processing' check(status in ('processing','completed','completed_with_errors','failed')), total_rows integer not null default 0, imported_count integer not null default 0, updated_count integer not null default 0, skipped_count integer not null default 0, failed_count integer not null default 0, created_by uuid not null references auth.users(id), created_at timestamptz not null default now(), completed_at timestamptz
);
create table public.parts_import_rows (
 id bigint generated always as identity primary key, batch_id uuid not null references public.parts_import_batches(id) on delete cascade, row_number integer not null, raw_data jsonb not null, normalized_data jsonb, status text not null check(status in ('pending','imported','updated','skipped','failed')), error_messages text[], matched_part_id uuid references public.parts_catalog(id) on delete set null, processed_at timestamptz
);
create table public.part_catalog_requests (
 id uuid primary key default gen_random_uuid(), part_name text not null, part_number text, brand_name text, vehicle_type text not null check(vehicle_type in ('Tractor','53'' Dry Van Trailer')), system_name text not null, estimated_customer_price numeric(12,2), supplier_name text, notes text, related_job_id uuid references public.jobs(id) on delete set null, status text not null default 'pending_review' check(status in ('pending_review','approved','rejected','merged')), requested_by uuid not null references auth.users(id), reviewed_by uuid references auth.users(id), reviewed_at timestamptz, catalog_part_id uuid references public.parts_catalog(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.parts_pricing_settings (
 id uuid primary key default gen_random_uuid(), default_markup_percent numeric(8,2) not null default 50, minimum_markup_percent numeric(8,2) not null default 25, emergency_multiplier numeric(8,3) not null default 1.25, core_charge_handling text not null default 'add' check(core_charge_handling in ('add','included','waive')), allow_manual_override boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), updated_by uuid references auth.users(id)
);
create table public.part_category_markup_rules (id uuid primary key default gen_random_uuid(), category_id uuid not null references public.part_categories(id) on delete cascade, markup_percent numeric(8,2) not null check(markup_percent>=0), minimum_markup_percent numeric(8,2) not null default 0, is_active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), updated_by uuid references auth.users(id), unique(category_id));

alter table public.parts_catalog add column compatible_brands text[] not null default '{}';
alter table public.parts_catalog alter column part_number drop not null;
alter table public.flat_rate_operation_parts add column recommendation_type text not null default 'required' check(recommendation_type in ('required','recommended','optional'));
alter table public.flat_rate_operation_parts add column default_selected boolean not null default true;

create index parts_import_rows_batch_idx on public.parts_import_rows(batch_id,row_number); create index part_requests_owner_idx on public.part_catalog_requests(requested_by,created_at desc); create index part_requests_status_idx on public.part_catalog_requests(status,created_at desc);
alter table public.parts_import_batches enable row level security; alter table public.parts_import_rows enable row level security; alter table public.part_catalog_requests enable row level security; alter table public.parts_pricing_settings enable row level security; alter table public.part_category_markup_rules enable row level security;
create policy "admin manage import batches" on public.parts_import_batches for all to authenticated using(public.is_app_admin()) with check(public.is_app_admin()); create policy "admin manage import rows" on public.parts_import_rows for all to authenticated using(public.is_app_admin()) with check(public.is_app_admin());
create policy "requester reads own requests" on public.part_catalog_requests for select to authenticated using(public.is_app_admin() or (public.is_active_app_user() and requested_by=auth.uid())); create policy "dispatcher creates requests" on public.part_catalog_requests for insert to authenticated with check(public.is_active_app_user() and requested_by=auth.uid() and status='pending_review'); create policy "admin manages requests" on public.part_catalog_requests for all to authenticated using(public.is_app_admin()) with check(public.is_app_admin());
create policy "active reads pricing rules" on public.parts_pricing_settings for select to authenticated using(public.is_active_app_user()); create policy "admin manages pricing rules" on public.parts_pricing_settings for all to authenticated using(public.is_app_admin()) with check(public.is_app_admin()); create policy "active reads category rules" on public.part_category_markup_rules for select to authenticated using(public.is_active_app_user()); create policy "admin manages category rules" on public.part_category_markup_rules for all to authenticated using(public.is_app_admin()) with check(public.is_app_admin());
insert into public.parts_pricing_settings default values;

create or replace function public.approve_part_catalog_request(p_request_id uuid,p_catalog_part_id uuid default null) returns uuid language plpgsql security definer set search_path='' as $$ declare r public.part_catalog_requests; new_id uuid; category_id uuid; brand_id uuid; begin if not public.is_app_admin() then raise exception 'Admin access required'; end if; select * into r from public.part_catalog_requests where id=p_request_id for update; if r.status<>'pending_review' then raise exception 'Request is not pending'; end if; new_id=p_catalog_part_id; if new_id is null then select id into category_id from public.part_categories where vehicle_type in (r.vehicle_type,'Both') and system_name=r.system_name order by vehicle_type desc limit 1; if category_id is null then insert into public.part_categories(name,system_name,vehicle_type,created_by) values(r.system_name,r.system_name,r.vehicle_type,auth.uid()) returning id into category_id; end if; if r.brand_name is not null then insert into public.part_brands(name,created_by) values(r.brand_name,auth.uid()) on conflict(name) do update set name=excluded.name returning id into brand_id; end if; insert into public.parts_catalog(part_name,part_number,category_id,brand_id,vehicle_type,system_name,estimated_low_price,estimated_selling_price,estimated_high_price,availability_status,dispatcher_notes,created_by) values(r.part_name,nullif(r.part_number,''),category_id,brand_id,r.vehicle_type,r.system_name,coalesce(r.estimated_customer_price,0),coalesce(r.estimated_customer_price,0),coalesce(r.estimated_customer_price,0),'Call to verify',r.notes,auth.uid()) returning id into new_id; end if; update public.part_catalog_requests set status='approved',catalog_part_id=new_id,reviewed_by=auth.uid(),reviewed_at=now(),updated_at=now() where id=p_request_id; return new_id; end $$;
grant execute on function public.approve_part_catalog_request(uuid,uuid) to authenticated;
